# Generated by Django 5.1.1 on 2024-09-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0005_shopproducts_shop_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="logo"
            ),
        ),
    ]
