# Generated by Django 5.1.1 on 2024-09-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0006_alter_brand_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nombre"),
        ),
    ]
