# Generated by Django 5.1.1 on 2024-10-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0007_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Imagen"
            ),
        ),
    ]
