# Generated by Django 5.1.1 on 2024-11-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0011_product_deleted_product_deleted_by_cascade"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created timestamp"
                    ),
                ),
                (
                    "updated_timestamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated timestamp"
                    ),
                ),
                (
                    "discount",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Descuento"
                    ),
                ),
                (
                    "extra_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Información Extra"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("U", "USD"), ("Z", "ZELLE")],
                        default="U",
                        max_length=1,
                        verbose_name="Método de Pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
            },
        ),
    ]
