# Generated by Django 5.1.1 on 2024-11-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0011_product_deleted_product_deleted_by_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='payment_method',
            field=models.CharField(choices=[('U', 'USD'), ('Z', 'ZELLE')], default='U', max_length=1, verbose_name='Método de Pago'),
        ),
    ]
