# Generated by Django 5.1.1 on 2024-11-21 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0013_sell_sell_group"),
        ("users_app", "0003_systemuser_shop"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sellgroup",
            options={
                "verbose_name": "Grupo de Venta",
                "verbose_name_plural": "Grupos de Ventas",
            },
        ),
        migrations.AddField(
            model_name="sellgroup",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sell_groups",
                to="users_app.systemuser",
                verbose_name="Vendedor",
            ),
        ),
    ]
