# Generated by Django 5.1.1 on 2025-02-06 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0014_alter_sellgroup_options_sellgroup_seller"),
        ("clients_app", "0002_client_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellgroup",
            name="client",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sells",
                to="clients_app.client",
                verbose_name="Cliente",
            ),
        ),
    ]
