# Generated by Django 5.1.1 on 2025-04-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0015_sellgroup_client"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "model"),
                name="name_model_unique",
                violation_error_message="Ya existe un producto con este nombre y para este modelo.",
            ),
        ),
    ]
