# Generated by Django 5.1.1 on 2025-06-04 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0015_sellgroup_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopproducts",
            name="cost_price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(limit_value=0.2)],
                verbose_name="Precio de costo",
            ),
        ),
        migrations.AlterField(
            model_name="shopproducts",
            name="sell_price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(limit_value=0.3)],
                verbose_name="Precio de venta",
            ),
        ),
    ]
