# Generated by Django 5.1.1 on 2025-07-04 00:59

from django.db import migrations, models


def add_shop_matanzas(apps, schema_editor):
    Shop = apps.get_model("business_app", "Shop")
    Shop.objects.get_or_create(name="Matanzas")


def disable_miami_shop(apps, schema_editor):
    Shop = apps.get_model("business_app", "Shop")
    Shop.objects.filter(name="Miami").update(enabled=False)
    Shop.objects.filter(name="Cuba").update(name="Ciego de Ávila")


def remove_shop_matanzas(apps, schema_editor):
    Shop = apps.get_model("business_app", "Shop")
    Shop.objects.filter(name="Matanzas").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0016_alter_shopproducts_cost_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Habilitado"),
        ),
        migrations.RunPython(add_shop_matanzas, remove_shop_matanzas),
        migrations.RunPython(disable_miami_shop, migrations.RunPython.noop),
    ]
