# Generated by Django 5.1.1 on 2025-07-11 23:13

from django.db import migrations
from PIL import Image


def resize_previous_images(apps, schema_editor):
    Product = apps.get_model("business_app", "Product")
    all_products = Product.objects.filter(image__isnull=False).only("image")
    for product in all_products:
        try:
            img = Image.open(product.image.path)
            resized_image = img.resize(size=(768, 768), reducing_gap=3.0)
            resized_image.save(product.image.path)
        except Exception:
            continue


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0017_shop_enabled"),
    ]

    operations = [
        migrations.RunPython(resize_previous_images, migrations.RunPython.noop),
    ]
