# Generated by Django 5.1.1 on 2025-07-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0018_rezise_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopProductInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created timestamp"
                    ),
                ),
                (
                    "updated_timestamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated timestamp"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "shop_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_product_inputs",
                        to="business_app.shopproducts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de Producto",
                "verbose_name_plural": "Entradas de Productos",
            },
        ),
        migrations.CreateModel(
            name="ShopProductInputGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created timestamp"
                    ),
                ),
                (
                    "updated_timestamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated timestamp"
                    ),
                ),
                (
                    "for_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="For date timestamp"
                    ),
                ),
                (
                    "extra_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Información Extra"
                    ),
                ),
                (
                    "shop_products",
                    models.ManyToManyField(
                        related_name="input_groups",
                        through="business_app.ShopProductInput",
                        to="business_app.shopproducts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de Entrada de Productos",
                "verbose_name_plural": "Grupos de Entrada de Productos",
            },
        ),
        migrations.AddField(
            model_name="shopproductinput",
            name="shop_product_input_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inputs",
                to="business_app.shopproductinputgroup",
            ),
        ),
    ]
