# Generated by Django 5.1.1 on 2026-03-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0018_rezise_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="catalog_url",
            field=models.SlugField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="URL catálogo",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="principal",
            field=models.BooleanField(default=False, verbose_name="Principal"),
        ),
        migrations.AddField(
            model_name="shop",
            name="type",
            field=models.CharField(
                choices=[
                    ("M", "Mecánica"),
                    ("T", "Tecnología"),
                    ("F", "Alimentos"),
                    ("O", "Otros"),
                ],
                default="M",
                max_length=1,
                verbose_name="Tipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="shop",
            constraint=models.UniqueConstraint(
                condition=models.Q(("principal", True)),
                fields=("principal",),
                name="unique_principal_shop",
            ),
        ),
    ]
