# Generated by Django 5.1.1 on 2025-07-24 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0019_shopproductinput_shopproductinputgroup_and_more"),
        ("users_app", "0003_systemuser_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopproductinputgroup",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="inputs",
                to="users_app.systemuser",
                verbose_name="Autor de la entrada",
            ),
        ),
    ]
