# Generated by Django 5.1.1 on 2025-07-24 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0020_shopproductinputgroup_author"),
        ("users_app", "0003_systemuser_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellgroup",
            name="for_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                null=True,
                verbose_name="For date timestamp",
            ),
        ),
        migrations.AddField(
            model_name="shopproductinput",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="inputs",
                to="users_app.systemuser",
                verbose_name="Autor de la entrada",
            ),
        ),
        migrations.AlterField(
            model_name="shopproductinputgroup",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="input_groups",
                to="users_app.systemuser",
                verbose_name="Autor de la entrada",
            ),
        ),
        migrations.AlterField(
            model_name="shopproductinputgroup",
            name="for_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                null=True,
                verbose_name="For date timestamp",
            ),
        ),
    ]
