# Generated by Django 5.1.1 on 2026-04-29 09:22

from django.db import migrations

destiny_shop_name = "Tecnología Ciego (Onel)"
source_shop_name = "Tecnología Ciego"


def populate_data(apps, schema_editor):
    Shop = apps.get_model("business_app", "Shop")
    Product = apps.get_model("business_app", "Product")
    Model = apps.get_model("business_app", "Model")
    Brand = apps.get_model("business_app", "Brand")
    ShopProducts = apps.get_model("business_app", "ShopProducts")

    destiny_shop, _ = Shop.objects.get_or_create(name=destiny_shop_name)
    source_shop = Shop.objects.filter(name=source_shop_name).first()

    datos_modificados = [
        ("Asus VivoBook", "Computadoras", "Portatil", 0, ""),
        ("Laptop Lenovo", "Computadoras", "Portatil", 0, ""),
        ("Laptop hp", "Computadoras", "Portatil", 0, ""),
        ("A 26", "Teléfonos", "Samsung", 0, ""),
        ("Redmi Note 15", "Teléfonos", "Xiaomi", 0, ""),
        ("Galaxy A17", "Teléfonos", "Samsung", 0, ""),
        ("Galaxy F17", "Teléfonos", "Samsung", 0, ""),
        ("Galaxy A16", "Teléfonos", "Samsung", 0, ""),
        ("Redmi 15C", "Teléfonos", "Xiaomi", 0, ""),
        ("Poco C71 8/128", "Teléfonos", "Xiaomi", 0, ""),
        ("Redmi A7PRO", "Teléfonos", "Xiaomi", 0, ""),
        ("Redmi 14C", "Teléfonos", "Xiaomi", 0, ""),
        ("Galaxy F07", "Teléfonos", "Samsung", 0, "19 sin cargador"),
        ("GO 3", "Teléfonos", "TECNO Spark", 0, ""),
        ("Galaxy a06", "Teléfonos", "Samsung", 0, "5 sin cargador"),
        ("Redmi A5", "Teléfonos", "Xiaomi", 0, ""),
        ("Redmi 9A de 4/64", "Teléfonos", "Xiaomi", 0, ""),
        ("Oppo A3x", "Teléfonos", "Xiaomi", 0, ""),
        ("A90", "Teléfonos", "Itel", 0, ""),
        ("Fire7", "Tables", "Tablet", 0, ""),
        ("C5L", "Teléfonos", "Blu", 0, ""),
        ("Philco p8", "Teléfonos", "Philco", 0, ""),
        ("Ventilador recargable F6", "Accesorios", "Electrodomésticos", 0, ""),
        ("w-2027", "Genérico", "Otros", 0, ""),
        ("Cargador portátil de 30000mah", "Accesorios", "Cargador portátil", 0, ""),
        ("Bocinas WS-570 Truck 🚚", "Accesorios", "Bocina", 0, ""),
        ("Bocina  DV 880", "Accesorios", "Bocina", 0, ""),
        ("Bocina zqs.6142", "Accesorios", "Bocina", 0, ""),
        ("Bocinas WS-1934 🚙", "Accesorios", "Bocina", 0, ""),
        ("Bocina DV 600", "Accesorios", "Bocina", 0, ""),
        ("Bocinas zqs 6165", "Accesorios", "Bocina", 0, ""),
        ("Bocina zqs 6166", "Accesorios", "Bocina", 0, ""),
        ("Bocina carro ws-590", "Accesorios", "Bocina", 0, ""),
        ("Bocina carro ws-591", "Accesorios", "Bocina", 0, ""),
        ("Bocinas WS-1968", "Accesorios", "Bocina", 0, ""),
        ("Lámpara recargable Solar Grande ☀", "Accesorios", "Electrodomésticos", 0, ""),
        ("Bocinas WS-580", "Accesorios", "Bocina", 0, ""),
        ("VBESTLIFE", "Genérico", "Otros", 0, ""),
        ("zqs-4271", "Accesorios", "Bocina", 0, ""),
        ("Cargador portátil de 20000mah", "Accesorios", "Cargador portátil", 0, ""),
        ("Lámpara recargable Solar pequeña", "Accesorios", "Electrodomésticos", 0, ""),
        ("MKtel dorado (3 cámaras)", "Teléfonos", "MKtel", 0, ""),
        (
            "Reloj Inteligente H33ProMax",
            "Accesorios",
            "SmartWatch Relojes inteligentes",
            0,
            "",
        ),
        ("Bocinas BT 1301", "Accesorios", "Bocina", 0, ""),
        ("Bocina  zqs1361", "Accesorios", "Bocina", 0, ""),
        ("Teléfono MKtel de teclas📱", "Teléfonos", "MKtel", 0, ""),
        (
            "Reloj Inteligente 🕒",
            "Accesorios",
            "SmartWatch Relojes inteligentes",
            0,
            "",
        ),
        ("Audífonos Casco inalámbricos  P9", "Accesorios", "Audífonos", 0, ""),
        ("Audífonos de chófer  Robóticos", "Accesorios", "Audífonos", 0, ""),
        ("Audífonos inalámbricos para Chofer", "Accesorios", "Audífonos", 0, ""),
        ("Cover con Perlas", "Accesorios", "Cover", 0, ""),
        ("Cover antichoque", "Accesorios", "Cover", 0, ""),
        ("Ventilador de mano 🤝", "Accesorios", "Electrodomésticos", 0, ""),
        ("Audífonos inalámbricos", "Accesorios", "Audífonos", 0, ""),
        ("Audífonos inalámbricos de cuello", "Lada", "1600", 0, ""),
        ("Micro SD de 64gb", "Almacenamiento", "Micro SD", 0, ""),
        ("reproductor MP3", "Accesorios", "Bocina", 0, ""),
        ("Memorias USB de 32 gb", "Almacenamiento", "Memorias USB", 0, ""),
        ("Soporte de teléfonos para carro HDS-098", "Genérico", "Otros", 0, ""),
        ("Memorias ADATA de 64 gb", "Almacenamiento", "Memorias USB", 0, ""),
        ("Micro SD de 32gb", "Almacenamiento", "Micro SD", 0, ""),
        ("Mouse 🖱", "Accesorios", "Mouse 🖱", 0, ""),
        ("Soporte para móviles", "Accesorios", "Soportes", 0, ""),
        ("Cargador para autos ABS Material", "Accesorios", "Cargadores", 0, ""),
        ("HDMI", "Accesorios", "Cables", 0, ""),
        ("Llaveros Stitch", "Genérico", "Otros", 0, ""),
        ("Cargador de Carga Rápida", "Accesorios", "Cargadores", 0, ""),
        ("Cargador 65w Carga Rapida", "Accesorios", "Cargadores", 0, ""),
        ("Cover convencional", "Accesorios", "Cover", 0, ""),
        ("Arañitas de cargar", "Accesorios", "Cargadores", 0, ""),
        ("Maquinilla de afeitar", "Genérico", "Otras partes y piezas", 0, ""),
        ("Cargador estándar tipo USB2 - tipo C", "Accesorios", "Cargadores", 0, ""),
        ("Cable largo usb-tipoc", "Accesorios", "Cables", 0, ""),
        ("Adaptadores micro SD", "Almacenamiento", "Micro SD", 0, ""),
        ("ndr-1742", "bosina", "", 0, ""),
        ("cargador de 2500", "", "", 0, ""),
        ("cargador portable p8", "", "", 0, ""),
        ("forro para audifono", "", "", 0, ""),
    ]

    # Crear ShopProducts en destiny_shop basados en datos_modificados
    for product_name, model_name, brand_name, quantity, extra_info in datos_modificados:
        # Brand.name max_length=25; truncar si es necesario
        brand = None
        if brand_name:
            normalized_brand_name = brand_name.strip()[:25]
            if normalized_brand_name:
                brand, _ = Brand.objects.get_or_create(name=normalized_brand_name)

        # Model.name es único globalmente; no se puede buscar por (name, brand).
        model = None
        if model_name and brand:
            model, _ = Model.objects.get_or_create(
                name=model_name,
                defaults={"brand": brand},
            )

        # Obtener o crear el Product
        # Note: Product.name no es unique, así que get_or_create sin model puede fallar.
        # Usamos filter().first() para obtener el primero existente o crear uno nuevo.
        product = Product.objects.filter(name=product_name).first()
        if not product:
            product, _ = Product.objects.get_or_create(
                name=product_name, defaults={"model": model}
            )

        # Buscar ShopProducts en "Tecnología Ciego" con el mismo nombre de producto para obtener precios
        cost_price = 1.0
        sell_price = 2.0
        sell_price_for_catalog = None

        if source_shop:
            source_shop_product = ShopProducts.objects.filter(
                shop=source_shop, product__name=product_name
            ).first()

            if source_shop_product:
                cost_price = source_shop_product.cost_price
                sell_price = source_shop_product.sell_price
                sell_price_for_catalog = source_shop_product.sell_price_for_catalog

        # Crear o actualizar el ShopProduct en destiny_shop
        if destiny_shop:
            ShopProducts.objects.update_or_create(
                shop=destiny_shop,
                product=product,
                defaults={
                    "quantity": quantity,
                    "extra_info": extra_info,
                    "cost_price": cost_price,
                    "sell_price": sell_price,
                    "sell_price_for_catalog": sell_price_for_catalog,
                },
            )


def reverse_populate_data(apps, schema_editor):
    Shop = apps.get_model("business_app", "Shop")
    ShopProducts = apps.get_model("business_app", "ShopProducts")

    destiny_shop = Shop.objects.filter(name=destiny_shop_name).first()
    if not destiny_shop:
        return

    product_names = [
        "Asus VivoBook",
        "Laptop Lenovo",
        "Laptop hp",
        "A 26",
        "Redmi Note 15",
        "Galaxy A17",
        "Galaxy F17",
        "Galaxy A16",
        "Redmi 15C",
        "Poco C71 8/128",
        "Redmi A7PRO",
        "Redmi 14C",
        "Galaxy F07",
        "GO 3",
        "Galaxy a06",
        "Redmi A5",
        "Redmi 9A de 4/64",
        "Oppo A3x",
        "A90",
        "Fire7",
        "C5L",
        "Philco p8",
        "Ventilador recargable F6",
        "w-2027",
        "Cargador portátil de 30000mah",
        "Bocinas WS-570 Truck 🚚",
        "Bocina  DV 880",
        "Bocina zqs.6142",
        "Bocinas WS-1934 🚙",
        "Bocina DV 600",
        "Bocinas zqs 6165",
        "Bocina zqs 6166",
        "Bocina carro ws-590",
        "Bocina carro ws-591",
        "Bocinas WS-1968",
        "Lámpara recargable Solar Grande ☀",
        "Bocinas WS-580",
        "VBESTLIFE",
        "zqs-4271",
        "Cargador portátil de 20000mah",
        "Lámpara recargable Solar pequeña",
        "MKtel dorado (3 cámaras)",
        "Reloj Inteligente H33ProMax",
        "Bocinas BT 1301",
        "Bocina  zqs1361",
        "Teléfono MKtel de teclas📱",
        "Reloj Inteligente 🕒",
        "Audífonos Casco inalámbricos  P9",
        "Audífonos de chófer  Robóticos",
        "Audífonos inalámbricos para Chofer",
        "Cover con Perlas",
        "Cover antichoque",
        "Ventilador de mano 🤝",
        "Audífonos inalámbricos",
        "Audífonos inalámbricos de cuello",
        "Micro SD de 64gb",
        "reproductor MP3",
        "Memorias USB de 32 gb",
        "Soporte de teléfonos para carro HDS-098",
        "Memorias ADATA de 64 gb",
        "Micro SD de 32gb",
        "Mouse 🖱",
        "Soporte para móviles",
        "Cargador para autos ABS Material",
        "HDMI",
        "Llaveros Stitch",
        "Cargador de Carga Rápida",
        "Cargador 65w Carga Rapida",
        "Cover convencional",
        "Arañitas de cargar",
        "Maquinilla de afeitar",
        "Cargador estándar tipo USB2 - tipo C",
        "Cable largo usb-tipoc",
        "Adaptadores micro SD",
    ]

    ShopProducts.objects.filter(
        shop=destiny_shop,
        product__name__in=product_names,
    ).hard_delete()


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0021_populate_data_for_new_shop"),
    ]

    operations = [migrations.RunPython(populate_data, reverse_populate_data)]
