# Generated by Django 5.1.1 on 2025-07-24 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0021_sellgroup_for_date_shopproductinput_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellgroup",
            name="for_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="For date timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="shopproductinputgroup",
            name="for_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="For date timestamp"
            ),
        ),
    ]
