# Generated by Django 5.1.1 on 2026-05-04 12:00


from django.db import migrations


def fix_swapped_brand_model_data(apps, schema_editor):
    """
    Corrige la inversión accidental de Brand y Model en la migración 0022.

    Contexto:
    --------
    La migración 0022 (populate_data_for_new_onel_shop) usó incorrectamente
    los campos model_name y brand_name de forma invertida. Esta migración
    busca y corrige esas referencias, reasignando Products a los Model
    correctos y eliminando Brand/Model erróneos que queden huérfanos.

    Inversión detectada: Cuando un Model.name es igual a un Brand.name,
    indica que fueron intercambiados durante 0022.

    Lógica:
    -------
    1. Identifica ShopProducts cuyas tiendas tengan shop__type="T".
    2. Para cada producto en esas tiendas, verifica si existe una inversión:
       - Un Model cuyo nombre coincide con otro Brand nombre (confusión)
    3. Si hay inversión, localiza el Model correcto y reasigna el producto.
    4. Elimina Model y Brand errados que queden sin referencias.

    Args:
        apps: Instancia de Apps de Django (para acceso a modelos históricos).
        schema_editor: SchemaEditor de Django (no usado en esta migración de datos).

    Returns:
        None. Los cambios se aplican directamente a la base de datos.
    """
    Product = apps.get_model("business_app", "Product")
    ShopProducts = apps.get_model("business_app", "ShopProducts")
    Model = apps.get_model("business_app", "Model")
    Brand = apps.get_model("business_app", "Brand")

    # Obtener IDs de productos afectados: productos en tiendas de tipo "T".
    affected_products = (
        ShopProducts.objects.filter(shop__type="T")
        .values_list("product_id", flat=True)
        .distinct()
    )

    candidate_models_to_delete = set()
    candidate_brands_to_delete = set()

    for product_id in affected_products:
        product = Product.objects.get(id=product_id)
        current_model = product.model
        current_brand = current_model.brand

        # Detectar par recíproco (A-B y B-A) que evidencia intercambio.
        reciprocal_model = Model.objects.filter(
            name=current_brand.name,
            brand__name=current_model.name,
        ).exclude(id=current_model.id).order_by("id").first()

        if reciprocal_model:
            # Criterio de seguridad: el más antiguo se considera correcto.
            # Solo corregimos si el modelo actual es el más nuevo (invertido).
            if current_model.id > reciprocal_model.id:
                product.model = reciprocal_model
                product.save(update_fields=["model"])

                # Registrar candidatos de limpieza; la validación de huérfanos
                # se realiza al final para evitar borrar referencias aún vivas.
                candidate_models_to_delete.add(current_model.id)
                candidate_brands_to_delete.add(current_brand.id)

    # Eliminar Model candidatos que realmente quedaron sin productos.
    for model_id in candidate_models_to_delete:
        if not Product.objects.filter(model_id=model_id).exists():
            Model.objects.filter(id=model_id).delete()

    # Eliminar Brand candidatos que realmente quedaron sin modelos.
    for brand_id in candidate_brands_to_delete:
        if not Model.objects.filter(brand_id=brand_id).exists():
            Brand.objects.filter(id=brand_id).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0022_populate_data_for_new_onel_shop"),
    ]

    operations = [
        migrations.RunPython(fix_swapped_brand_model_data, migrations.RunPython.noop),
    ]
