# Generated by Django 5.1.1 on 2026-05-04 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0022_alter_sellgroup_for_date_and_more"),
        ("business_app", "0023_fix_swapped_brand_model_onel_shop"),
    ]

    operations = []
