# Generated by Django 5.1.1 on 2026-09-11 14:41

import os
from datetime import date

import django.core.validators
from django.db import migrations, models
from django.db.models import F, Value
from django.db.models.functions import Concat


WHOLESALE_SHOP_NAME = "Tienda al por mayor"


def delete_unused_products(apps, schema_editor):
    ShopProducts = apps.get_model("business_app", "ShopProducts")
    Product = apps.get_model("business_app", "Product")

    today = date.today()
    all_product_ids = set(
        Product.objects.values_list("id", flat=True)
    )
    used_product_ids = set(
        ShopProducts.objects.values_list("product_id", flat=True).distinct()
    )
    today_product_ids = set(
        Product.objects.filter(created_timestamp__date=today).values_list(
            "id", flat=True
        )
    )
    ShopProducts.objects.filter(product_id__in=today_product_ids).delete()
    deleted_count = Product.objects.filter(id__in=today_product_ids).delete()[0]
    if deleted_count:
        print("Deleted %s unused products" % deleted_count)

def reset_wholesale_shop_products(apps, schema_editor):
    ShopProducts = apps.get_model("business_app", "ShopProducts")
    wholesale_shop_product_ids = list(
        ShopProducts.objects.filter(shop__name=WHOLESALE_SHOP_NAME).values_list(
            "id", flat=True
        )
    )
    ShopProducts.objects.filter(id__in=wholesale_shop_product_ids).update(
        quantity=0,
    )
    try:
        GenericLog = apps.get_model("common", "GenericLog")
        ContentType = apps.get_model("contenttypes", "ContentType")
    except LookupError:
        from django.apps import apps as real_apps

        GenericLog = real_apps.get_model("common", "GenericLog")
        ContentType = real_apps.get_model("contenttypes", "ContentType")

    content_type = ContentType.objects.get_for_model(ShopProducts)

    GenericLog.objects.filter(
        content_type=content_type,
        object_id__in=wholesale_shop_product_ids,
    ).delete()
    delete_unused_products(apps, schema_editor)



def reset_wholesale_shop_products_feed(apps, schema_editor):
    # product, marca_modelo, quantity, extra_info, sell_price, wholesale_price
    PRODUCTS = (
        ("Aforador", "Geely - CK", 11, None, 85, 75),
        ("Alfombra de maletero", "Geely - CK", 2, None, 100, 80),
        ("Alfombra de pizarra", "Geely - CK", 1, None, 35, 30),
        ("Alternador", "Geely - CK", 2, None, 145, 130),
        (
            "Amortiguadores traseros desarmados",
            "Geely - CK",
            9,
            "Par Armados",
            270,
            250,
        ),
        ("Bandas de freno con ABS", "Geely - CK", 7, "Juego", 25, 20),
        (
            "Base de amortiguador delantero",
            "Geely - CK",
            24,
            "juegos (base + calzo)",
            25,
            22,
        ),
        ("Bieletas Traseras", "Geely - CK", 17, "Par", 18, 15),
        ("Bobina", "Geely - CK", 24, None, 35, 30),
        ("Bomba de cloche esclava", "Geely - CK", 4, None, 20, 18),
        ("Bomba de cloche Principal", "Geely - CK", 12, None, 26, 24),
        ("Bomba de freno con hidrovac", "Geely - CK", 12, None, 130, 120),
        ("Bomba hidráulica", "Geely - CK", 11, None, 135, 120),
        ("Botaguas", "Geely - CK", 24, "Juego", 50, 45),
        ("Botonera pequeña", "Geely - CK", 48, None, 8, 6),
        ("Botonera Principal", "Geely - CK", 9, None, 20, 16),
        (
            "Bóvedas",
            "Geely - CK",
            38,
            "Juego de 4 (solo tenemos juegos delanteros)",
            15,
            10,
        ),
        ("Brazos limpiaparabrisas", "Geely - CK", 10, "juego", 25, 20),
        ("Bujes de Parrillas", "Geely - CK", 12, "juegos", 15, 12.5),
        ("Cable de abrir maletero y combustible", "Geely - CK", 16, None, 25, 20),
        ("Cable de emergencia", "Geely - CK", 5, None, 25, 25),
        ("Cables de Bujías", "Geely - CK", 5, "Genuinos", 30, 25),
        ("Caja de fusibles euro 4", "Geely - CK", 1, None, 120, 120),
        ("Calzos del motor antipar", "Geely - CK", 22, None, 32, 28),
        ("Calzos del motor grande", "Geely - CK", 3, None, 40, 35),
        ("Calzos del motor izquierdo", "Geely - CK", 1, None, 32, 28),
        ("Careta Delantera antigua", "Geely - CK", 11, None, 45, 40),
        ("Careta Delantera moderna", "Geely - CK", 9, None, 50, 45),
        ("Chapaletas o guarda polvos", "Geely - CK", 19, "juego", 16, 14),
        ("Collarín", "Geely - CK", 20, None, 20, 18),
        ("Compresor de Aire Acondicionado", "Geely - CK", 4, None, 230, 200),
        ("Conmutador de luces y Claxon", "Geely - CK", 11, "Juegos", 45, 40),
        ("Correa de Alternador", "Geely - CK", 4, "unidades", 15, 12),
        ("Correa de distribución", "Geely - CK", 7, None, 22, 18),
        ("Correa hidráulica", "Geely - CK", 19, None, 6, 4.5),
        ("Correas de compresor", "Geely - CK", 19, "4pk", 9, 7),
        ("Cremallera", "Geely - CK", 2, None, 185, 180),
        ("Depósito agua limpiaparabrisas", "Geely - CK", 10, None, 45, 40),
        ("Disco de Cloche", "Geely - CK", 8, None, 45, 40),
        ("Discos de freno con y sin ABS", "Geely - CK", 7, "Par con ABS", 65, 58),
        ("Electro ventilador", "Geely - CK", 19, "por unidad", 45, 40),
        ("Embellecedor de cierre de Maletero", "Geely - CK", 0, None, 40, 40),
        ("Embellecedor de frente de distribución", "Geely - CK", 4, None, 16, 14),
        ("Embellecedor de parabrisas", "Geely - CK", 39, "Par", 45, 40),
        ("Filtros de aceite", "Geely - CK", 70, None, 6, 4.5),
        ("Filtros de Gasolina", "Geely - CK", 79, None, 7, 5.5),
        ("Forro de palanca de emergencia", "Geely - CK", 6, None, 35, 30),
        ("Homocinética corta", "Geely - CK", 5, None, 100, 95),
        ("Homocinética Larga", "Geely - CK", 5, None, 100, 95),
        ("Juego de Chucho", "Geely - CK", 8, "Juego", 45, 40),
        ("Junta de puerta delantera I", "Geely - CK", 2, None, 15, 15),
        ("Junta de puerta trasera I", "Geely - CK", 2, None, 15, 15),
        ("Juntas de puertas", "Geely - CK", 12, "Juego de puertas y maletero", 80, 75),
        ("Kit de cloche", "Geely - CK", 1, None, 155, 155),
        ("Kit de juntas", "Geely - CK", 2, None, 55, 50),
        ("Mangueras de radiador tipo A", "Geely - CK", 10, "Unidad", 12.5, None),
        ("Mangueras de radiador tipo B", "Geely - CK", 10, "cada  una", 12.5, None),
        ("Manillas Externas", "Geely - CK", 14, None, 55, 50),
        ("Manillas interiores Plásticas", "Geely - CK", 9, "Juego las 4", 25, 20),
        ("Módulo de Control", "Geely - CK", 3, None, 90, 80),
        ("Motor de limpiaparabrisas", "Geely - CK", 7, None, 45, 40),
        ("Neblineros delanteros", "Geely - CK", 8, "Par", 45, 40),
        ("Pantallas delanteras (Focos)", "Geely - CK", 4, "Juego", 190, 170),
        ("Paños de puerta Traseros", "Geely - CK", 1, "Par Trasero", 60, 45),
        ("Parabrisas", "Geely - CK", 4, None, 200, 180),
        ("Pasillos o Estribos plásticos", "Geely - CK", 11, "par", 45, 40),
        ("Paso a Paso", "Geely - CK", 18, None, 22, 18),
        ("Pastillas de freno", "Geely - CK", 12, "Juego", 30, 25),
        ("Pinzas de freno delanteras con ABS", "Geely - CK", 4, "Par", 120, 100),
        ("Pinzas de freno delanteras sin ABS", "Geely - CK", 5, "Par", 90, 80),
        ("Pizarra moderna", "Geely - CK", 8, None, 90, 75),
        ("Pizarra moderna", "Geely - CK", 8, None, 90, 75),
        ("Plato opresor del cloche", "Geely - CK", 13, None, 80, 70),
        ("Purificador", "Geely - CK", 1, None, 40, 35),
        (
            "Regulador de ventanilla delantera",
            "Geely - CK",
            14,
            "Cremallera eléctrica para puertas",
            40,
            35,
        ),
        ("Reparación de Homocinética", "Geely - CK", 6, "Cajitas", 35, 35),
        ("Sensor de oxígeno", "Geely - CK", 9, None, 40, 35),
        ("Sensor de oxígeno delphi", "Geely - CK", 6, None, 40, 35),
        ("Sensor de Temperatura", "Geely - CK", 50, None, 15, 12),
        ("Sensor de velocidad mecanico", "Geely - CK", 2, None, 30, 25),
        ("Sensor Map", "Geely - CK", 15, None, 30, 25),
        ("Sensor Stop", "Geely - CK", 3, None, 12, 10),
        ("Sistema cinturón seguridad", "Geely - CK", 26, None, 30, 20),
        ("Tapa de radiador", "Geely - CK", 29, None, 8, 6),
        ("Tensor", "Geely - CK", 3, None, 15, 15),
        ("Termostato", "Geely - CK", 10, None, 15, 12),
        ("Válvula de control de recipiente PCV", "Geely - CK", 20, None, 18, 15),
        ("Inyectores", "Geely - CK", 10, "Juego de 4", 40, 35),
        ("Aforador", "Geely - Emgrand 718", 13, None, 85, 75),
        ("Alfombra de maletero", "Geely - Emgrand 718", 6, None, 80, 80),
        ("Alfombra de pizarra", "Geely - Emgrand 718", 1, None, 35, None),
        (
            "Arnés de Cables y caja de Fusibles Exterior",
            "Geely - Emgrand 718",
            1,
            None,
            250,
            None,
        ),
        (
            "Bieletas delanteras",
            "Geely - Emgrand 718",
            2,
            "Par (hay dos derechas adicionales)",
            35,
            None,
        ),
        ("Bisagras de puertas", "Geely - Emgrand 718", 4, "cada una", 5, None),
        (
            "Bobinas de encendido electrónica Independiente",
            "Geely - Emgrand 718",
            16,
            "independiente",
            40,
            35,
        ),
        ("Bomba de aceite", "Geely - Emgrand 718", 9, None, 65, 60),
        ("Bomba de agua", "Geely - Emgrand 718", 18, None, 45, 40),
        ("Bomba de cloche esclava", "Geely - Emgrand 718", 5, None, 20, 18),
        ("Bomba de cloche principal", "Geely - Emgrand 718", 4, None, 35, 30),
        ("Botaguas", "Geely - Emgrand 718", 13, "juego de 4", 60, 45),
        ("Botonera  principal", "Geely - Emgrand 718", 20, None, 30, 20),
        ("Bóvedas", "Geely - Emgrand 718", 6, "juego de 4", 90, 75),
        (
            "Brazo de control de muñón de dirección",
            "Geely - Emgrand 718",
            3,
            "cada uno",
            50,
            None,
        ),
        ("Bujes de barra estabilizadora", "Geely - Emgrand 718", 26, None, 8, 5),
        (
            "Cable de abrir maletero y combustible",
            "Geely - Emgrand 718",
            10,
            None,
            25,
            20,
        ),
        ("Cable de Cambios", "Geely - Emgrand 718", 15, None, 70, 50),
        ("Cables de Bujías", "Geely - Emgrand 718", 12, None, 30, 25),
        ("Cables de emergencia", "Geely - Emgrand 718", 1, None, 50, 40),
        ("Calzos del motor grande", "Geely - Emgrand 718", 2, "Juego", 55, None),
        ("Calzos del motor pequeño", "Geely - Emgrand 718", 2, "Juego", 45, None),
        ("Carcasa de control de llaves", "Geely - Emgrand 718", 2, "cada una", 15, 15),
        ("Careta Delantera", "Geely - Emgrand 718", 8, None, 45, 40),
        ("Chapaletas", "Geely - Emgrand 718", 17, "juego de 4", 25, 20),
        ("Cinta de Timón", "Geely - Emgrand 718", 7, "22 slash 09", 50, 40),
        ("Cremallera de Dirección", "Geely - Emgrand 718", 12, None, 220, 190),
        ("Defensa delantera", "Geely - Emgrand 718", 2, None, 150, 150),
        (
            "Depósito de agua de limpiaparabrisas",
            "Geely - Emgrand 718",
            6,
            None,
            55,
            45,
        ),
        ("Disco de cloche", "Geely - Emgrand 718", 6, None, 45, 40),
        (
            "Discos de freno delanteros",
            "Geely - Emgrand 718",
            2,
            "Pares y uno adicional",
            85,
            70,
        ),
        ("Electro ventilador", "Geely - Emgrand 718", 3, None, 150, 125),
        ("Embellecedor de capó", "Geely - Emgrand 718", 1, None, 15, 10),
        ("Embellecedor de motor", "Geely - Emgrand 718", 2, None, 60, 50),
        (
            "embellecedor Neblineros delanteros modernos",
            "Geely - Emgrand 718",
            7,
            "Par",
            None,
            None,
        ),
        ("Embellecedores de manillas", "Geely - Emgrand 718", 1, "Juego de 4", 50, 50),
        ("Filtro de aire acondicionado", "Geely - Emgrand 718", 1, None, 15, 12),
        ("filtro de aire de la cabina", "Geely - Emgrand 718", 1, None, 15, 12),
        ("Filtros de aceite", "Geely - Emgrand 718", 39, None, 6, 5),
        ("Filtros de Gasolina", "Geely - Emgrand 718", 36, None, 8, 6),
        ("Filtros de motor", "Geely - Emgrand 718", 30, None, 15, None),
        ("Flauta con inyectores", "Geely - Emgrand 718", 7, None, 130, 100),
        ("forro de maletero", "Geely - Emgrand 718", 5, None, 80, 70),
        ("Homocinética corta", "Geely - Emgrand 718", 1, None, 120, None),
        ("Homocinética Larga", "Geely - Emgrand 718", 1, None, 120, None),
        ("Intermitentes espejos", "Geely - Emgrand 718", 2, "Par", 25, 20),
        ("Juego barredores de puertas", "Geely - Emgrand 718", 2, "Juego", 80, 70),
        ("Juego de Chucho", "Geely - Emgrand 718", 9, "Juego", 80, 70),
        ("Juego de Espejos Retrovisores", "Geely - Emgrand 718", 4, "Par", 100, 85),
        ("Juego de Pistones", "Geely - Emgrand 718", 1, "juego", 85, None),
        (
            "Juegos de sistema limpiaparabrisas con motor",
            "Geely - Emgrand 718",
            1,
            None,
            75,
            None,
        ),
        ("Juegos soporte defensa", "Geely - Emgrand 718", 9, "Juego", 15, None),
        ("Junta de puerta delantera D", "Geely - Emgrand 718", 1, None, 20, None),
        ("Juntas de puertas", "Geely - Emgrand 718", 2, "Juego de 4", 80, None),
        ("Kit de cloche", "Geely - Emgrand 718", 7, None, 180, None),
        ("Kit de juntas", "Geely - Emgrand 718", 1, None, 65, None),
        (
            "Manguera de succión de aire acondicionado",
            "Geely - Emgrand 718",
            10,
            None,
            None,
            None,
        ),
        ("Mangueras del purificador", "Geely - Emgrand 718", 2, None, 15, None),
        ("Manillas Externas", "Geely - Emgrand 718", 3, "Juegos", 90, None),
        (
            "Manillas interiores de metal",
            "Geely - Emgrand 718",
            3,
            "Juego de 4",
            80,
            None,
        ),
        ("Módulo de aceleración", "Geely - Emgrand 718", 5, None, 140, None),
        (
            "Motor soplador de aire acondicionado",
            "Geely - Emgrand 718",
            4,
            None,
            75,
            60,
        ),
        ("Neblineros delanteros Antiguos", "Geely - Emgrand 718", 1, "Par", 85, None),
        (
            "Neblineros delanteros modernos",
            "Geely - Emgrand 718",
            7,
            "Par con embellecedores",
            90,
            80,
        ),
        ("Palanca de emergencia", "Geely - Emgrand 718", 2, None, 50, None),
        (
            "Panel de control Aire acondicionado",
            "Geely - Emgrand 718",
            3,
            None,
            60,
            None,
        ),
        (
            "Pantalla de música",
            "Geely - Emgrand 718",
            1,
            "cámara de retroceso",
            170,
            140,
        ),
        ("Pantallas delanteras Modernas", "Geely - Emgrand 718", 2, "Par", 350, None),
        ("Pantallas traseras", "Geely - Emgrand 718", 4, "Par Led", 150, None),
        ("Parabrisas", "Geely - Emgrand 718", 2, None, 450, None),
        ("Parrillas delanteras", "Geely - Emgrand 718", 9, "Juego", 130, 110),
        ("Pasillos o Estribos plásticos", "Geely - Emgrand 718", 4, "Par", 50, 40),
        ("Pastillas de freno delanteras", "Geely - Emgrand 718", 21, "Juego", 30, 20),
        ("Pastillas de freno traseras", "Geely - Emgrand 718", 1, "juego", 30, None),
        ("Pedal Electrónico", "Geely - Emgrand 718", 3, None, 50, None),
        (
            "Pinzas de freno traseras",
            "Geely - Emgrand 718",
            6,
            "Par más una izquierda suelta",
            150,
            None,
        ),
        ("Plato opresor del cloche", "Geely - Emgrand 718", 1, None, 80, None),
        ("Purificador", "Geely - Emgrand 718", 15, None, 45, 40),
        ("Reparación de Homocinética", "Geely - Emgrand 718", 10, "cajitas", 35, 30),
        ("Rodamientos delanteros", "Geely - Emgrand 718", 16, "c/u", 50, 40),
        (
            "Rodamientos traseros con Cubo de Rueda",
            "Geely - Emgrand 718",
            8,
            None,
            60,
            45,
        ),
        (
            "Rótula de cabezal de dirección inferior",
            "Geely - Emgrand 718",
            20,
            None,
            45,
            40,
        ),
        ("Sensor de luz de Marcha Atrás", "Geely - Emgrand 718", 1, None, 15, None),
        ("Sensor Temperatura", "Geely - Emgrand 718", 20, "Por unidad", 18, 15),
        ("Sistema cinturón seguridad", "Geely - Emgrand 718", 21, None, 35, 30),
        ("Tensor", "Geely - Emgrand 718", 10, None, 55, 45),
        ("Alfombra de maletero", "Geely - Emgrand 820", 4, None, 85, 70),
        ("Alfombra de pizarra", "Geely - Emgrand 820", 1, None, 40, None),
        ("Alternador", "Geely - Emgrand 820", 24, None, 170, 150),
        (
            "Amortiguadores traseros desarmados",
            "Geely - Emgrand 820",
            6,
            "par",
            None,
            None,
        ),
        (
            "Amortiguadores traseros desarmados",
            "Geely - Emgrand 820",
            1,
            "Par",
            None,
            None,
        ),
        ("Bieletas delanteras", "Geely - Emgrand 820", 12, "Par", 35, None),
        (
            "Bomba de aceite Motor Chino",
            "Geely - Emgrand 820",
            4,
            "motor chino",
            100,
            80,
        ),
        ("Bomba de agua Motor chino", "Geely - Emgrand 820", 7, "Motor Chino", 60, 55),
        ("Bomba hidráulica Motor Chino", "Geely - Emgrand 820", 8, None, 140, 125),
        ("Bomba hidráulica Motor Mitsubishi", "Geely - Emgrand 820", 2, None, 140, 125),
        ("Botagua", "Geely - Emgrand 820", 10, "Juego de 4", 50, None),
        ("Bóvedas", "Geely - Emgrand 820", 10, "juegos delanteros", 60, None),
        ("Bujías", "Geely - Emgrand 820", 10, "Juego", 25, 20),
        ("Cable abrir capó", "Geely - Emgrand 820", 7, None, 10, 8),
        (
            "Cable de abrir maletero y combustible",
            "Geely - Emgrand 820",
            8,
            None,
            25,
            20,
        ),
        ("Cable de Cambios", "Geely - Emgrand 820", 7, None, 100, None),
        ("Cable de emergencia", "Geely - Emgrand 820", 3, None, 70, None),
        ("Calzos del motor antipar", "Geely - Emgrand 820", 6, None, 55, None),
        ("Calzos del motor pequeño", "Geely - Emgrand 820", 6, None, 45, None),
        ("Collarín", "Geely - Emgrand 820", 5, None, 35, None),
        ("Compresor", "Geely - Emgrand 820", 6, None, 240, None),
        ("Cremallera de Dirección", "Geely - Emgrand 820", 7, None, 300, None),
        ("Cubos de rueda delanteros", "Geely - Emgrand 820", 7, None, None, None),
        ("Defensa delantera", "Geely - Emgrand 820", 1, None, 180, None),
        ("defensa trasera", "Geely - Emgrand 820", 2, None, 100, None),
        (
            "Depósito de agua de limpiaparabrisas",
            "Geely - Emgrand 820",
            6,
            None,
            65,
            55,
        ),
        ("Disco de Cloche", "Geely - Emgrand 820", 6, None, 55, 50),
        ("Disco de freno delantero", "Geely - Emgrand 820", 4, "pares", 80, None),
        ("Esféricas", "Geely - Emgrand 820", 3, "Cada una (hay 3 izq)", 18, None),
        (
            "Extremos finales de Dirección (Yoquis)",
            "Geely - Emgrand 820",
            1,
            None,
            10,
            None,
        ),
        ("Forro de palanca", "Geely - Emgrand 820", 6, None, 35, None),
        ("Homocinética corta motor chino", "Geely - Emgrand 820", 6, None, 130, None),
        ("Homocinética larga  motor chino", "Geely - Emgrand 820", 5, None, 170, None),
        ("Juego de tapasoles", "Geely - Emgrand 820", 8, "unidades", 25, None),
        ("Kit de distribución", "Geely - Emgrand 820", 1, None, 100, None),
        (
            "Kit de juntas motor Chino",
            "Geely - Emgrand 820",
            1,
            "se pasa uno a Mitsubishi por error se agregó aquí",
            80,
            None,
        ),
        ("Motor de arranque", "Geely - Emgrand 820", 8, None, 100, None),
        ("Neblineros delanteros", "Geely - Emgrand 820", 5, "Par", 70, None),
        ("Parabrisas", "Geely - Emgrand 820", 5, None, 600, None),
        ("Parrillas delanteras", "Geely - Emgrand 820", 6, "juegos", 150, None),
        ("Planetarias", "Geely - Emgrand 820", 6, None, 20, None),
        ("Plato opresor del cloche", "Geely - Emgrand 820", 5, None, 80, None),
        ("Porta pinza de freno delantero", "Geely - Emgrand 820", 1, None, 15, None),
        ("Porta pinza de freno trasero", "Geely - Emgrand 820", 1, None, 15, None),
        (
            "Portapinza de freno trasero derecho",
            "Geely - Emgrand 820",
            1,
            "juego",
            25,
            None,
        ),
        ("Radiador Mitsubishi", "Geely - Emgrand 820", 1, None, 150, None),
        ("Reparación Homocinética", "Geely - Emgrand 820", 5, "cajitas", 40, None),
        (
            "Sensor de oxígeno delphi Motor Mitsubishi",
            "Geely - Emgrand 820",
            2,
            None,
            40,
            None,
        ),
        ("Sensor de velocidad", "Geely - Emgrand 820", 1, None, 30, None),
        (
            "Sensor posición del árbol de leva motor chino",
            "Geely - Emgrand 820",
            1,
            None,
            25,
            None,
        ),
        ("Sistema cinturón seguridad", "Geely - Emgrand 820", 9, None, 30, None),
        ("Sistema de palanca de cambios", "Geely - Emgrand 820", 2, None, 85, None),
        ("Tapa tanque gasolina", "Geely - Emgrand 820", 3, None, 20, None),
        (
            "Juego de juntas para puertas y maleteros",
            "Geely - Emgrand 820",
            4,
            "juegos completos de puertas y maletero",
            80,
            None,
        ),
        ("Juntas traseras de puertas", "Geely - Emgrand 820", 3, "Sueltas", 15, None),
        (
            "Juntas delanteras de puertas",
            "Geely - Emgrand 820",
            1,
            "Sueltas",
            15,
            None,
        ),
        ("Juntas de maletero", "Geely - Emgrand 820", 1, "Sueltas", 15, None),
        ("Aforador", "Geely - Emgrand GC6", 15, None, 90, 80),
        ("Alfombra de maletero", "Geely - Emgrand GC6", 1, None, 80, None),
        ("Alternador", "Geely - Emgrand GC6", 5, None, 140, 125),
        (
            "Bieletas delanteras",
            "Geely - Emgrand GC6",
            2,
            "Pare - Atrás no lleva",
            22,
            None,
        ),
        ("Bobina de encendido", "Geely - Emgrand GC6", 4, None, 35, 30),
        ("Bomba de agua automático", "Geely - Emgrand GC6", 2, None, 45, 40),
        ("Botaguas", "Geely - Emgrand GC6", 18, "Juegos", 55, 45),
        ("Botonera Principal", "Geely - Emgrand GC6", 1, None, 50, None),
        ("Bóvedas", "Geely - Emgrand GC6", 3, "juego de 4", 85, 70),
        (
            "Buje control de eje trasero",
            "Geely - Emgrand GC6",
            14,
            "cada uno",
            None,
            None,
        ),
        (
            "Cable de abrir maletero y combustible",
            "Geely - Emgrand GC6",
            18,
            None,
            30,
            22,
        ),
        ("Cable de emergencia", "Geely - Emgrand GC6", 2, None, 65, None),
        ("Caja de fusibles", "Geely - Emgrand GC6", 5, None, 120, 95),
        ("Caretas Delanteras", "Geely - Emgrand GC6", 7, None, 100, 80),
        ("Chapaletas", "Geely - Emgrand GC6", 15, "Juego de 4", 25, 20),
        ("Cinta de Timón", "Geely - Emgrand GC6", 7, "09-22-00", 50, 40),
        ("Correa de Alternador", "Geely - Emgrand GC6", 2, None, 15, 12),
        ("Cremallera de Dirección", "Geely - Emgrand GC6", 3, None, 180, None),
        (
            "Defensa delantera plastico grande",
            "Geely - Emgrand GC6",
            9,
            None,
            100,
            None,
        ),
        ("Depósito de agua limpiaparabrisas", "Geely - Emgrand GC6", 18, None, 55, 40),
        ("Disco de Cloche", "Geely - Emgrand GC6", 5, None, 55, 45),
        ("Discos de freno", "Geely - Emgrand GC6", 2, "par", 65, None),
        ("Embellecedor de motor", "Geely - Emgrand GC6", 3, None, 70, 55),
        ("Esféricas", "Geely - Emgrand GC6", 16, "Unidad", 45, None),
        ("Filtro de aire motor automático", "Geely - Emgrand GC6", 7, None, 15, None),
        (
            "Flauta con inyectores de motor automático",
            "Geely - Emgrand GC6",
            4,
            None,
            80,
            None,
        ),
        ("Forro de palanca", "Geely - Emgrand GC6", 4, None, 35, None),
        ("Insignia Careta", "Geely - Emgrand GC6", 3, None, None, None),
        (
            "Juego de barredores de puertas",
            "Geely - Emgrand GC6",
            3,
            "Juego de 4",
            80,
            None,
        ),
        ("Juegos brazos limpiaparabrisas", "Geely - Emgrand GC6", 3, None, 30, None),
        (
            "Juegos de sistema limpiaparabrisas con motor",
            "Geely - Emgrand GC6",
            8,
            None,
            85,
            70,
        ),
        ("Juegos soporte defensa", "Geely - Emgrand GC6", 8, None, 20, None),
        (
            "Juntas de puertas",
            "Geely - Emgrand GC6",
            9,
            "Juego de 4 puertas y maletero",
            90,
            None,
        ),
        ("KIT de juntas  Motor automático", "Geely - Emgrand GC6", 5, None, 70, None),
        (
            "Manillas interiores Plásticas",
            "Geely - Emgrand GC6",
            13,
            "Juego de 4",
            30,
            None,
        ),
        ("Módulo de Aceleración", "Geely - Emgrand GC6", 4, None, 130, 100),
        ("Motor de arranque", "Geely - Emgrand GC6", 15, None, 100, 85),
        (
            "Motor soplador de aire acondicionado",
            "Geely - Emgrand GC6",
            1,
            None,
            70,
            None,
        ),
        ("Neblineros delanteros", "Geely - Emgrand GC6", 2, "Par", 75, None),
        ("Neblineros traseros", "Geely - Emgrand GC6", 1, "Par", 55, None),
        (
            "Panel de control de aire acondicionado antiguo",
            "Geely - Emgrand GC6",
            7,
            None,
            50,
            None,
        ),
        ("Pantallas delanteras", "Geely - Emgrand GC6", 16, "Par", 260, None),
        ("Parrillas delanteras", "Geely - Emgrand GC6", 6, "Juegos", 125, None),
        ("Paso a paso", "Geely - Emgrand GC6", 19, None, 25, None),
        ("Pastillas de freno delanteras", "Geely - Emgrand GC6", 15, "Juego", 35, 28),
        ("Planetarias", "Geely - Emgrand GC6", 5, "juego y 1 suelta", 15, None),
        ("Plato opresor del cloche", "Geely - Emgrand GC6", 4, None, 80, None),
        ("Purificador mecánico", "Geely - Emgrand GC6", 22, None, 45, None),
        (
            "Regulador de ventanilla delantera derecha",
            "Geely - Emgrand GC6",
            25,
            None,
            40,
            30,
        ),
        ("Reparación de Homocinética", "Geely - Emgrand GC6", 2, "Cajitas", 35, None),
        ("Rodamientos delanteros", "Geely - Emgrand GC6", 8, None, 55, 45),
        (
            "Rodamientos traseros con Cubo de Rueda",
            "Geely - Emgrand GC6",
            4,
            "cada uno",
            60,
            45,
        ),
        (
            "embellecedor de defensa plateado",
            "Geely - Emgrand GC6",
            4,
            "Juegos",
            60,
            50,
        ),
        (
            "embellecedor de defensa plateado v laterales",
            "Geely - Emgrand GC6",
            5,
            "Pares",
            60,
            None,
        ),
        ("Junta de puerta delantera I", "Geely - Emgrand GC6", 2, None, 15, None),
        ("Parabrisas", "Geely - Emgrand GC6", 4, None, 400, None),
        ("plastico central de defensa", "Geely - Emgrand GC6", 10, None, 50, None),
        ("Cangreja", "Geely - Emgrand GC9", 3, "Juego", 120, None),
        ("Parrillas", "Geely - Emgrand GC9", 3, "Juego", 200, None),
        (
            "Alerón con stop Universal",
            "Genérico - Otras partes y piezas",
            1,
            None,
            40,
            None,
        ),
        (
            "Bombillos led Mejor calidad H4",
            "Genérico - Otras partes y piezas",
            1,
            "Par",
            25,
            None,
        ),
        ("Clip de Geely", "Genérico - Otras partes y piezas", 5, "Paquete", 8, None),
        ("Letras EC820", "Genérico - Otras partes y piezas", 2, None, 15, None),
        (
            "Líquido para limpiar inyectores",
            "Genérico - Otras partes y piezas",
            9,
            None,
            4,
            None,
        ),
        (
            "Luz EMGRAM de puertas",
            "Genérico - Otras partes y piezas",
            2,
            "Par",
            40,
            None,
        ),
        ("Módulo GPS", "Genérico - Otras partes y piezas", 2, None, 80, None),
        ("Olores de silicona", "Genérico - Otras partes y piezas", 1, None, 5, None),
        (
            "Paquete de bombillos led variados",
            "Genérico - Otras partes y piezas",
            1,
            None,
            10,
            None,
        ),
        (
            "Pomos octanaje combustible",
            "Genérico - Otras partes y piezas",
            48,
            None,
            4,
            None,
        ),
        ("Aro Embellecedor de timón", "Kia - Río", 1, None, 25, None),
        ("Bujías Punta de Iridio", "Kia - Río", 5, "juegos de 4", 30, None),
        (
            "Embellecedor de agarradera de techo",
            "Kia - Río",
            2,
            "juego de 3 piezas",
            20,
            None,
        ),
        ("Embellecedor de cinturón", "Kia - Río", 1, "solo 2", 20, None),
        ("Embellecedores de botonera de Timón", "Kia - Río", 1, "Par", 40, None),
        ("Embellecedores de Pasillos", "Kia - Río", 1, "Juego de 4", 60, None),
        ("Insignia de Timón", "Kia - Río", 2, "c/u", 10, None),
        ("Kit de distribución", "Geely - Emgrand 718", 1, None, None, None),
        ("Juego de Chucho", "Geely - Emgrand GC6", 1, None, None, None),
        ("Encendedor de cigarros", "Geely - Emgrand 718", 5, None, None, None),
        ("Botón de estacionario (Stop)", "Geely - Emgrand 718", 2, None, None, None),
        ("Bujes de barra estabilizadora", "Geely - CK", 8, None, None, None),
        ("Cierre de puertas", "Geely - Emgrand 820", 1, "Juego de 4", None, None),
        ("Bobinas de encendido", "Geely - Emgrand 820", 8, None, None, None),
        (
            "Soporte de montaje de defensa trasera",
            "Geely - Emgrand 718",
            1,
            "Juego",
            None,
            None,
        ),
        ("Acople del motor soplador", "Geely - CK", 2, None, None, None),
        ("Luz grande de salón", "Geely - Emgrand 718", 5, None, None, None),
        ("Luz pequeña de salón", "Geely - Emgrand 718", 3, None, None, None),
        ("Junta de maletero", "Geely - Emgrand GC6", 1, None, None, None),
        ("Alargador de caña de dirección", "Geely - Emgrand 718", 3, None, None, None),
        ("Anillo de goma", "Geely - CK", 1, None, None, None),
    )
    ShopProducts = apps.get_model("business_app", "ShopProducts")
    Product = apps.get_model("business_app", "Product")
    Brand = apps.get_model("business_app", "Brand")
    Model = apps.get_model("business_app", "Model")
    GenericLog = apps.get_model("common", "GenericLog")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Shop = apps.get_model("business_app", "Shop")

    shopproduct_content_type = ContentType.objects.get_for_model(ShopProducts)
    my_shop = Shop.objects.get(name=WHOLESALE_SHOP_NAME)
    FIXED_COST_PRICE = 0.2

    existing_map = {}
    shop_products = (
        ShopProducts.objects.annotate(
            model_brand=Concat(
                F("product__model__brand__name"),
                Value(" - "),
                F("product__model__name"),
            )
        )
        .select_related("product__model__brand")
        .filter(shop=my_shop)
    )
    for obj in shop_products:
        existing_map.setdefault(
            (obj.product.name.lower(), obj.model_brand.lower()), []
        ).append(obj)

    product_map = {}
    products = Product.objects.annotate(
        model_brand=Concat(
            F("model__brand__name"),
            Value(" - "),
            F("model__name"),
        )
    )
    for product in products:
        product_map.setdefault(
            (product.name.lower(), product.model_brand.lower()), []
        ).append(product)

    unmatched_records = []

    created_map = {}
    existing_updates = {}
    pending_created = []
    pending_logs = {}

    for (
        incoming_product_name,
        incoming_model_brand,
        incoming_quantity,
        incoming_extra_info,
        sell_price,
        incoming_wholesale_price,
    ) in PRODUCTS:
        key = (incoming_product_name.lower(), incoming_model_brand.lower())
        effective_sell_price = sell_price or 0.3
        default_cost_price = min(FIXED_COST_PRICE, round(effective_sell_price * 0.9, 2))

        matches = existing_map.get(key)
        if matches is None:
            matches = created_map.get(key)

        if matches:
            for obj in matches:
                obj.quantity = incoming_quantity
                obj.extra_info = incoming_extra_info
                obj.sell_price = effective_sell_price
                obj.wholesale_price = incoming_wholesale_price
                if obj.pk:
                    existing_updates[obj.pk] = obj
            pending_logs[id(matches[0])] = (matches[0], incoming_quantity)
            continue

        product_matches = product_map.get(key)
        if product_matches:
            product = product_matches[0]
            obj = ShopProducts(
                shop=my_shop,
                product=product,
                quantity=incoming_quantity,
                extra_info=incoming_extra_info,
                cost_price=default_cost_price,
                sell_price=effective_sell_price,
                wholesale_price=incoming_wholesale_price,
            )
            pending_created.append(obj)
            created_map[key] = [obj]
            pending_logs[id(obj)] = (obj, incoming_quantity)
            continue

        brand_name, _, model_name = incoming_model_brand.partition(" - ")
        if not brand_name or not model_name:
            unmatched_records.append(
                (
                    incoming_product_name,
                    incoming_model_brand,
                    incoming_quantity,
                    incoming_extra_info,
                    sell_price,
                    incoming_wholesale_price,
                )
            )
            continue
        brand, _ = Brand.objects.get_or_create(
            name__iexact=brand_name, defaults={"name": brand_name}
        )
        model, _ = Model.objects.get_or_create(
            name__iexact=model_name, defaults={"name": model_name, "brand": brand}
        )
        if model.brand_id != brand.id:
            model.brand = brand
            model.save()
        product = Product.objects.filter(
            name__iexact=incoming_product_name, model=model
        ).first()
        if product is None:
            product = Product(name=incoming_product_name, model=model)
            product.save()
        obj = ShopProducts(
            shop=my_shop,
            product=product,
            quantity=incoming_quantity,
            extra_info=incoming_extra_info,
            cost_price=default_cost_price,
            sell_price=effective_sell_price,
            wholesale_price=incoming_wholesale_price,
        )
        pending_created.append(obj)
        created_map[key] = [obj]
        pending_logs[id(obj)] = (obj, incoming_quantity)
        continue

    if existing_updates:
        ShopProducts.objects.bulk_update(
            existing_updates.values(),
            ["quantity", "extra_info", "sell_price", "wholesale_price"],
        )
    if pending_created:
        ShopProducts.objects.bulk_create(pending_created)

    logged_ids = [obj.pk for obj, _ in pending_logs.values()]
    if logged_ids:
        GenericLog.objects.filter(
            content_type=shopproduct_content_type, object_id__in=logged_ids
        ).delete()
        GenericLog.objects.bulk_create(
            [
                GenericLog(
                    content_type=shopproduct_content_type,
                    object_id=obj.pk,
                    performed_action="C",
                    details={"quantity": {"old_value": None, "new_value": quantity}},
                    extra_log_info=" en CONTEO INICIAL",
                )
                for obj, quantity in pending_logs.values()
            ]
        )
    if unmatched_records:
        output_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))),
            "unmatched_records.txt",
        )
        with open(output_path, "w", encoding="utf-8") as f:
            for record in unmatched_records:
                f.write(repr(record) + "\n")


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0027_shopproducts_wholesale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopproducts",
            name="wholesale_price",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(limit_value=0.3)],
                verbose_name="Precio al por mayor",
            ),
        ),
        migrations.RunPython(
            code=reset_wholesale_shop_products_feed,
            reverse_code=reset_wholesale_shop_products,
        ),
    ]
