# Generated by Django 5.1.1 on 2026-09-11 14:41

import django.core.validators
from django.db import migrations, models


WHOLESALE_SHOP_NAME = "Tienda al por mayor"


def reset_wholesale_shop_products(apps, schema_editor):
    ShopProducts = apps.get_model("business_app", "ShopProducts")
    ShopProducts.objects.filter(shop__name=WHOLESALE_SHOP_NAME).update(
        quantity=0,
        sell_price=0.3,
        sell_price_for_catalog=None,
        wholesale_price=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0027_shopproducts_wholesale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='wholesale_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.3)], verbose_name='Precio al por mayor'),
        ),
        migrations.RunPython(
            code=reset_wholesale_shop_products,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
