# Generated by Django 5.1.1 on 2026-09-11 18:01

from django.db import migrations
from django.db.models import Q


WHOLESALE_SHOP_NAME = "Tienda al por mayor"


def clean_wholesale_shop_product_logs(apps, schema_editor):
    ShopProducts = apps.get_model("business_app", "ShopProducts")
    GenericLog = apps.get_model("common", "GenericLog")
    ContentType = apps.get_model("contenttypes", "ContentType")

    wholesale_shop_product_ids = list(
        ShopProducts.objects.filter(shop__name=WHOLESALE_SHOP_NAME).values_list(
            "id", flat=True
        )
    )
    content_type = ContentType.objects.get_for_model(ShopProducts)

    logs_to_delete = GenericLog.objects.filter(
        content_type=content_type,
        object_id__in=wholesale_shop_product_ids,
    ).filter(~Q(performed_action="C"))

    deleted_count, _ = logs_to_delete.delete()
    print(
        f"Eliminados {deleted_count} logs de ShopProducts "
        f"de la tienda {WHOLESALE_SHOP_NAME!r} con accion distinta de 'C'."
    )


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0028_alter_shopproducts_wholesale_price"),
    ]

    operations = [
        migrations.RunPython(
            code=clean_wholesale_shop_product_logs,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
