# Generated by Django 5.1.1 on 2026-09-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0028_alter_shopproducts_wholesale_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'model'), name='unique_product_model'),
        ),
    ]
