# Generated by Django 5.1.1 on 2026-09-22 12:02

from django.db import migrations, models


def nullify_cost_price(apps, schema_editor):
    ShopProducts = apps.get_model("business_app", "ShopProducts")
    ShopProducts.objects.all().update(cost_price=None)


def noop_reverse(apps, schema_editor):
    # Intentional no-op: previous cost values cannot be restored once nulled.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0029_product_unique_product_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopproducts",
            name="cost_price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Precio de costo"
            ),
        ),
        migrations.RunPython(nullify_cost_price, noop_reverse),
    ]
