# Generated by Django 5.1.1 on 2026-09-14 08:23

from itertools import product

from django.db import migrations
import os

import django.core.validators
from django.db import migrations, models
from django.db.models import F, Value
from django.db.models.functions import Concat


WHOLESALE_SHOP_NAME = "Tienda al por mayor"


def populate_shopproducts(apps, schema_editor):
    # product, marca_modelo, quantity, extra_info, sell_price, wholesale_price
    PRODUCTOS = (
        ("Alfombra de maletero", "Geely - CK", 2, None, 100, 80)(
            "Amortiguadores traseros desarmados",
            "Geely - CK",
            9,
            "Par Armados",
            270,
            250,
        )(
            "Base de amortiguador delantero",
            "Geely - CK",
            24,
            "juegos (base + calzo)",
            25,
            22,
        )("Botonera pequeña", "Geely - CK", 48, None, 8, 6)(
            "Calzos del motor izquierdo", "Geely - CK", 1, None, 32, 28
        )("Collarín", "Geely - CK", 20, None, 20, 18)(
            "Disco de Cloche", "Geely - CK", 8, None, 45, 40
        )("Discos de freno con y sin ABS", "Geely - CK", 7, "Par con ABS", 65, 58)(
            "Embellecedor de cierre de Maletero", "Geely - CK", 0, None, 40, 40
        )("Embellecedor de frente de distribución", "Geely - CK", 4, None, 16, 14)(
            "Forro de palanca de emergencia", "Geely - CK", 6, None, 35, 30
        )("Homocinética corta", "Geely - CK", 5, None, 100, 95)(
            "Homocinética Larga", "Geely - CK", 5, None, 100, 95
        )("Junta de puerta delantera I", "Geely - CK", 2, None, 15, 15)(
            "Junta de puerta trasera I", "Geely - CK", 2, None, 15, 15
        )("Mangueras de radiador tipo A", "Geely - CK", 10, "Unidad", 12.5, None)(
            "Mangueras de radiador tipo B", "Geely - CK", 10, "cada  una", 12.5, None
        )("Pinzas de freno delanteras sin ABS", "Geely - CK", 5, "Par", 90, 80)(
            "Pizarra moderna", "Geely - CK", 8, None, 90, 75
        )("Pizarra moderna", "Geely - CK", 8, None, 90, 75)(
            "Plato opresor del cloche", "Geely - CK", 13, None, 80, 70
        )(
            "Regulador de ventanilla delantera",
            "Geely - CK",
            14,
            "Cremallera eléctrica para puertas",
            40,
            35,
        )("Sensor de oxígeno delphi", "Geely - CK", 6, None, 40, 35)(
            "Sensor de velocidad mecanico", "Geely - CK", 2, None, 30, 25
        )("Sensor Stop", "Geely - CK", 3, None, 12, 10)(
            "Tensor", "Geely - CK", 3, None, 15, 15
        )("Válvula de control de recipiente PCV", "Geely - CK", 20, None, 18, 15)(
            "Alfombra de maletero", "Geely - Emgrand 718", 6, None, 80, 80
        )("Alfombra de pizarra", "Geely - Emgrand 718", 1, None, 35, None)(
            "Bisagras de puertas", "Geely - Emgrand 718", 4, "cada una", 5, None
        )(
            "Bobinas de encendido electrónica Independiente",
            "Geely - Emgrand 718",
            16,
            "independiente",
            40,
            35,
        )("Botonera  principal", "Geely - Emgrand 718", 20, None, 30, 20)(
            "Brazo de control de muñón de dirección",
            "Geely - Emgrand 718",
            3,
            "cada uno",
            50,
            None,
        )("Calzos del motor grande", "Geely - Emgrand 718", 2, "Juego", 55, None)(
            "Calzos del motor pequeño", "Geely - Emgrand 718", 2, "Juego", 45, None
        )("Disco de cloche", "Geely - Emgrand 718", 6, None, 45, 40)(
            "Embellecedor de capó", "Geely - Emgrand 718", 1, None, 15, 10
        )(
            "embellecedor Neblineros delanteros modernos",
            "Geely - Emgrand 718",
            7,
            "Par",
            None,
            None,
        )("Embellecedores de manillas", "Geely - Emgrand 718", 1, "Juego de 4", 50, 50)(
            "Filtro de aire acondicionado", "Geely - Emgrand 718", 1, None, 15, 12
        )("filtro de aire de la cabina", "Geely - Emgrand 718", 1, None, 15, 12)(
            "Filtros de motor", "Geely - Emgrand 718", 30, None, 15, None
        )("forro de maletero", "Geely - Emgrand 718", 5, None, 80, 70)(
            "Homocinética corta", "Geely - Emgrand 718", 1, None, 120, None
        )("Homocinética Larga", "Geely - Emgrand 718", 1, None, 120, None)(
            "Intermitentes espejos", "Geely - Emgrand 718", 2, "Par", 25, 20
        )("Juego de Chucho", "Geely - Emgrand 718", 9, "Juego", 80, 70)(
            "Juego de Pistones", "Geely - Emgrand 718", 1, "juego", 85, None
        )(
            "Juegos de sistema limpiaparabrisas con motor",
            "Geely - Emgrand 718",
            1,
            None,
            75,
            None,
        )("Junta de puerta delantera D", "Geely - Emgrand 718", 1, None, 20, None)(
            "Kit de juntas", "Geely - Emgrand 718", 1, None, 65, None
        )(
            "Manguera de succión de aire acondicionado",
            "Geely - Emgrand 718",
            10,
            None,
            None,
            None,
        )("Mangueras del purificador", "Geely - Emgrand 718", 2, None, 15, None)(
            "Manillas Externas", "Geely - Emgrand 718", 3, "Juegos", 90, None
        )(
            "Manillas interiores de metal",
            "Geely - Emgrand 718",
            3,
            "Juego de 4",
            80,
            None,
        )("Módulo de aceleración", "Geely - Emgrand 718", 5, None, 140, None)(
            "Neblineros delanteros Antiguos", "Geely - Emgrand 718", 1, "Par", 85, None
        )("Palanca de emergencia", "Geely - Emgrand 718", 2, None, 50, None)(
            "Pantallas traseras", "Geely - Emgrand 718", 4, "Par Led", 150, None
        )("Parabrisas", "Geely - Emgrand 718", 2, None, 450, None)(
            "Pasillos o Estribos plásticos", "Geely - Emgrand 718", 4, "Par", 50, 40
        )("Pastillas de freno traseras", "Geely - Emgrand 718", 1, "juego", 30, None)(
            "Plato opresor del cloche", "Geely - Emgrand 718", 1, None, 80, None
        )(
            "Rodamientos traseros con Cubo de Rueda",
            "Geely - Emgrand 718",
            8,
            None,
            60,
            45,
        )(
            "Rótula de cabezal de dirección inferior",
            "Geely - Emgrand 718",
            20,
            None,
            45,
            40,
        )("Sensor de luz de Marcha Atrás", "Geely - Emgrand 718", 1, None, 15, None)(
            "Sensor Temperatura", "Geely - Emgrand 718", 20, "Por unidad", 18, 15
        )("Sistema cinturón seguridad", "Geely - Emgrand 718", 21, None, 35, 30)(
            "Alfombra de maletero", "Geely - Emgrand 820", 4, None, 85, 70
        )("Alfombra de pizarra", "Geely - Emgrand 820", 1, None, 40, None)(
            "Amortiguadores traseros desarmados",
            "Geely - Emgrand 820",
            6,
            "par",
            None,
            None,
        )(
            "Amortiguadores traseros desarmados",
            "Geely - Emgrand 820",
            1,
            "Par",
            None,
            None,
        )("Bujías", "Geely - Emgrand 820", 10, "Juego", 25, 20)(
            "Collarín", "Geely - Emgrand 820", 5, None, 35, None
        )("Cremallera de Dirección", "Geely - Emgrand 820", 7, None, 300, None)(
            "defensa trasera", "Geely - Emgrand 820", 2, None, 100, None
        )("Disco de Cloche", "Geely - Emgrand 820", 6, None, 55, 50)(
            "Disco de freno delantero", "Geely - Emgrand 820", 4, "pares", 80, None
        )("Esféricas", "Geely - Emgrand 820", 3, "Cada una (hay 3 izq)", 18, None)(
            "Extremos finales de Dirección (Yoquis)",
            "Geely - Emgrand 820",
            1,
            None,
            10,
            None,
        )("Forro de palanca", "Geely - Emgrand 820", 6, None, 35, None)(
            "Kit de distribución", "Geely - Emgrand 820", 1, None, 100, None
        )(
            "Kit de juntas motor Chino",
            "Geely - Emgrand 820",
            1,
            "se pasa uno a Mitsubishi por error se agregó aquí",
            80,
            None,
        )("Motor de arranque", "Geely - Emgrand 820", 8, None, 100, None)(
            "Parabrisas", "Geely - Emgrand 820", 5, None, 600, None
        )("Planetarias", "Geely - Emgrand 820", 6, None, 20, None)(
            "Plato opresor del cloche", "Geely - Emgrand 820", 5, None, 80, None
        )("Porta pinza de freno delantero", "Geely - Emgrand 820", 1, None, 15, None)(
            "Porta pinza de freno trasero", "Geely - Emgrand 820", 1, None, 15, None
        )(
            "Portapinza de freno trasero derecho",
            "Geely - Emgrand 820",
            1,
            "juego",
            25,
            None,
        )(
            "Sensor de oxígeno delphi Motor Mitsubishi",
            "Geely - Emgrand 820",
            2,
            None,
            40,
            None,
        )("Sensor de velocidad", "Geely - Emgrand 820", 1, None, 30, None)(
            "Sensor posición del árbol de leva motor chino",
            "Geely - Emgrand 820",
            1,
            None,
            25,
            None,
        )("Sistema cinturón seguridad", "Geely - Emgrand 820", 9, None, 30, None)(
            "Tapa tanque gasolina", "Geely - Emgrand 820", 3, None, 20, None
        )(
            "Juego de juntas para puertas y maleteros",
            "Geely - Emgrand 820",
            4,
            "juegos completos de puertas y maletero",
            80,
            None,
        )("Juntas traseras de puertas", "Geely - Emgrand 820", 3, "Sueltas", 15, None)(
            "Juntas delanteras de puertas",
            "Geely - Emgrand 820",
            1,
            "Sueltas",
            15,
            None,
        )("Juntas de maletero", "Geely - Emgrand 820", 1, "Sueltas", 15, None)(
            "Alfombra de maletero", "Geely - Emgrand GC6", 1, None, 80, None
        )(
            "Bieletas delanteras",
            "Geely - Emgrand GC6",
            2,
            "Pare - Atrás no lleva",
            22,
            None,
        )("Botonera Principal", "Geely - Emgrand GC6", 1, None, 50, None)(
            "Buje control de eje trasero",
            "Geely - Emgrand GC6",
            14,
            "cada uno",
            None,
            None,
        )("Correa de Alternador", "Geely - Emgrand GC6", 2, None, 15, 12)(
            "Cremallera de Dirección", "Geely - Emgrand GC6", 3, None, 180, None
        )(
            "Defensa delantera plastico grande",
            "Geely - Emgrand GC6",
            9,
            None,
            100,
            None,
        )("Disco de Cloche", "Geely - Emgrand GC6", 5, None, 55, 45)(
            "Filtro de aire motor automático", "Geely - Emgrand GC6", 7, None, 15, None
        )("Forro de palanca", "Geely - Emgrand GC6", 4, None, 35, None)(
            "Insignia Careta", "Geely - Emgrand GC6", 3, None, None, None
        )(
            "Juegos de sistema limpiaparabrisas con motor",
            "Geely - Emgrand GC6",
            8,
            None,
            85,
            70,
        )("KIT de juntas  Motor automático", "Geely - Emgrand GC6", 5, None, 70, None)(
            "Módulo de Aceleración", "Geely - Emgrand GC6", 4, None, 130, 100
        )("Plato opresor del cloche", "Geely - Emgrand GC6", 4, None, 80, None)(
            "Purificador mecánico", "Geely - Emgrand GC6", 22, None, 45, None
        )(
            "Regulador de ventanilla delantera derecha",
            "Geely - Emgrand GC6",
            25,
            None,
            40,
            30,
        )(
            "embellecedor de defensa plateado",
            "Geely - Emgrand GC6",
            4,
            "Juegos",
            60,
            50,
        )(
            "embellecedor de defensa plateado v laterales",
            "Geely - Emgrand GC6",
            5,
            "Pares",
            60,
            None,
        )("Junta de puerta delantera I", "Geely - Emgrand GC6", 2, None, 15, None)(
            "plastico central de defensa", "Geely - Emgrand GC6", 10, None, 50, None
        )(
            "Alerón con stop Universal",
            "Genérico - Otras partes y piezas",
            1,
            None,
            40,
            None,
        )(
            "Bombillos led Mejor calidad H4",
            "Genérico - Otras partes y piezas",
            1,
            "Par",
            25,
            None,
        )("Clip de Geely", "Genérico - Otras partes y piezas", 5, "Paquete", 8, None)(
            "Letras EC820", "Genérico - Otras partes y piezas", 2, None, 15, None
        )(
            "Líquido para limpiar inyectores",
            "Genérico - Otras partes y piezas",
            9,
            None,
            4,
            None,
        )(
            "Luz EMGRAM de puertas",
            "Genérico - Otras partes y piezas",
            2,
            "Par",
            40,
            None,
        )("Módulo GPS", "Genérico - Otras partes y piezas", 2, None, 80, None)(
            "Olores de silicona", "Genérico - Otras partes y piezas", 1, None, 5, None
        )(
            "Paquete de bombillos led variados",
            "Genérico - Otras partes y piezas",
            1,
            None,
            10,
            None,
        )(
            "Pomos octanaje combustible",
            "Genérico - Otras partes y piezas",
            48,
            None,
            4,
            None,
        )("Aro Embellecedor de timón", "Kia - Río", 1, None, 25, None)(
            "Bujías Punta de Iridio", "Kia - Río", 5, "juegos de 4", 30, None
        )(
            "Embellecedor de agarradera de techo",
            "Kia - Río",
            2,
            "juego de 3 piezas",
            20,
            None,
        )("Embellecedor de cinturón", "Kia - Río", 1, "solo 2", 20, None)(
            "Embellecedores de botonera de Timón", "Kia - Río", 1, "Par", 40, None
        )("Embellecedores de Pasillos", "Kia - Río", 1, "Juego de 4", 60, None)(
            "Insignia de Timón", "Kia - Río", 2, "c/u", 10, None
        )("Kit de distribución", "Geely - Emgrand 718", 1, None, None, None)(
            "Encendedor de cigarros", "Geely - Emgrand 718", 5, None, None, None
        )("Botón de estacionario (Stop)", "Geely - Emgrand 718", 2, None, None, None)(
            "Bujes de barra estabilizadora", "Geely - CK", 8, None, None, None
        )("Cierre de puertas", "Geely - Emgrand 820", 1, "Juego de 4", None, None)(
            "Soporte de montaje de defensa trasera",
            "Geely - Emgrand 718",
            1,
            "Juego",
            None,
            None,
        )("Acople del motor soplador", "Geely - CK", 2, None, None, None)(
            "Luz grande de salón", "Geely - Emgrand 718", 5, None, None, None
        )("Luz pequeña de salón", "Geely - Emgrand 718", 3, None, None, None)(
            "Junta de maletero", "Geely - Emgrand GC6", 1, None, None, None
        )("Alargador de caña de dirección", "Geely - Emgrand 718", 3, None, None, None)(
            "Anillo de goma", "Geely - CK", 1, None, None, None
        ),
    )
    ShopProducts = apps.get_model("business_app", "ShopProducts")
    Product = apps.get_model("business_app", "Product")
    Shop = apps.get_model("business_app", "Shop")
    GenericLog = apps.get_model("common", "GenericLog")
    ContentType = apps.get_model("contenttypes", "ContentType")
    unmatched_records = []
    my_shop = Shop.objects.get(name=WHOLESALE_SHOP_NAME)

    for (
        incoming_product_name,
        incoming_model_brand,
        incoming_quantity,
        incoming_extra_info,
        sell_price,
        incoming_wholesale_price,
    ) in PRODUCTOS:
        product_queryset = Product.objects.annotate(
            model_brand=Concat(
                F("model__brand__name"),
                Value(" - "),
                F("model__name"),
            )
        ).filter(
            name=incoming_product_name,
            model_brand=incoming_model_brand,
        )
    
        if not product_queryset.exists():
            unmatched_records.append(
                (
                    incoming_product_name,
                    incoming_model_brand,
                    incoming_quantity,
                    incoming_extra_info,
                    sell_price,
                    incoming_wholesale_price,
                )
            )
            continue
        product = product_queryset.first()
        created_shopproduct = ShopProducts.objects.create(
            shop=my_shop,
            product=product,
            quantity=incoming_quantity,
            extra_info=incoming_extra_info,
            sell_price=sell_price or 0.3,
            wholesale_price=incoming_wholesale_price,
        )

        content_type = ContentType.objects.get_for_model(ShopProducts)
        GenericLog.objects.filter(content_type=content_type, object_id=created_shopproduct.id).delete()
        GenericLog.objects.create(
            content_type=content_type,
            object_id=created_shopproduct.id,
            performed_action="C",
            details={"quantity": {"old_value": None, "new_value": incoming_quantity}},
            extra_log_info=" en CONTEO INICIAL",
        )
    output_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))),
        "unmatched_records_2nd.txt",
    )
    with open(output_path, "w", encoding="utf-8") as f:
        for record in unmatched_records:
            f.write(repr(record) + "\n")


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0029_cleanup_shopproducts_logs_wholesale_shop"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_shopproducts,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
