# Generated by Django 5.1.1 on 2026-09-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0030_alter_shopproducts_cost_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rack", models.PositiveSmallIntegerField(verbose_name="Rack")),
                (
                    "section",
                    models.CharField(max_length=1, verbose_name="Sección"),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="Número")),
            ],
            options={
                "verbose_name": "Pallet",
                "verbose_name_plural": "Pallets",
            },
        ),
        migrations.AddField(
            model_name="shopproducts",
            name="pallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="business_app.pallet",
                verbose_name="Pallet",
            ),
        ),
    ]
