# Generated by Django 5.1.1 on 2026-09-22 00:00

import django.db.models.deletion
from django.db import migrations, models


def populate_pallets(apps, schema_editor):
    Pallet = apps.get_model("business_app", "Pallet")

    for rack in range(1, 3):
        for section in "ABCDEFG":
            for number in range(1, 7):
                Pallet.objects.get_or_create(
                    rack=rack,
                    section=section,
                    number=number,
                )


def unpopulate_pallets(apps, schema_editor):
    Pallet = apps.get_model("business_app", "Pallet")

    Pallet.objects.filter(
        rack__in=[1, 2],
        section__in=list("ABCDEFG"),
        number__in=[1, 2, 3, 4, 5, 6],
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0030_alter_shopproducts_cost_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rack", models.PositiveSmallIntegerField(verbose_name="Rack")),
                (
                    "section",
                    models.CharField(max_length=1, verbose_name="Sección"),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="Número")),
            ],
            options={
                "verbose_name": "Pallet",
                "verbose_name_plural": "Pallets",
            },
        ),
        migrations.AddField(
            model_name="shopproducts",
            name="pallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="business_app.pallet",
                verbose_name="Pallet",
            ),
        ),
        migrations.AddConstraint(
            model_name="pallet",
            constraint=models.UniqueConstraint(
                fields=("rack", "section", "number"),
                name="unique_pallet_rack_section_number",
            ),
        ),
        migrations.RunPython(populate_pallets, unpopulate_pallets),

    ]
