# Generated by Django 5.1.1 on 2026-09-25 00:00

import django.db.models.deletion
from django.db import migrations, models


WHOLESALE_SHOP_NAME = "Tienda al por mayor"


def set_shop_for_existing_pallets(apps, schema_editor):
    Pallet = apps.get_model("business_app", "Pallet")
    Shop = apps.get_model("business_app", "Shop")

    wholesale_shop, _ = Shop.objects.get_or_create(
        name=WHOLESALE_SHOP_NAME,
        defaults={
            "extra_info": "Auto-creada por migración para asignar pallets",
            "type": "M",
            "enabled": True,
            "principal": False,
        },
    )

    Pallet.objects.filter(shop__isnull=True).update(shop=wholesale_shop)


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0031_pallet_shopproducts_pallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="pallet",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="business_app.shop",
                verbose_name="Tienda",
            ),
        ),
        migrations.RunPython(
            set_shop_for_existing_pallets,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="pallet",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="business_app.shop",
                verbose_name="Tienda",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="pallet",
            name="unique_pallet_rack_section_number",
        ),
        migrations.AddConstraint(
            model_name="pallet",
            constraint=models.UniqueConstraint(
                fields=("shop", "rack", "section", "number"),
                name="unique_pallet_shop_rack_section_number",
            ),
        ),
    ]
