# Generated by Django 5.1.1 on 2026-09-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0032_pallet_shop_fk_and_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellgroup",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Total",
            ),
        ),
    ]
