# Generated by Django 5.1.1 on 2026-10-06

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations
from django.db.models import F, FloatField, Sum, Value
from django.db.models.functions import Coalesce


TWO_DECIMALS = Decimal("0.01")


def backfill_sellgroup_total(apps, schema_editor):
    SellGroup = apps.get_model("business_app", "SellGroup")
    Sell = apps.get_model("business_app", "Sell")

    group_ids = list(
        SellGroup.objects.filter(total=Decimal("0.00")).values_list("id", flat=True)
    )
    if not group_ids:
        return

    totals_by_group = {
        row["sell_group_id"]: Decimal(str(row["computed_total"] or 0)).quantize(
            TWO_DECIMALS,
            rounding=ROUND_HALF_UP,
        )
        for row in Sell.objects.filter(sell_group_id__in=group_ids)
        .values("sell_group_id")
        .annotate(
            computed_total=Sum(
                F("quantity")
                * Coalesce(
                    F("shop_product__sell_price"),
                    Value(0.0),
                    output_field=FloatField(),
                )
            )
        )
    }

    groups_to_update = []
    for group in SellGroup.objects.filter(
        id__in=totals_by_group.keys(), total=Decimal("0.00")
    ):
        computed_total = totals_by_group[group.id]
        if computed_total > Decimal("0.00"):
            group.total = computed_total
            groups_to_update.append(group)

    if groups_to_update:
        SellGroup.objects.bulk_update(groups_to_update, ["total"])


def noop_reverse(apps, schema_editor):
    # Intentional no-op: resetting totals to zero would destroy corrected history.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0033_sellgroup_total"),
    ]

    operations = [
        migrations.RunPython(backfill_sellgroup_total, noop_reverse),
    ]
