from django.core.management import call_command
from django.core.management.base import BaseCommand
from termcolor import colored
from apps.business_app.models import Shop, Product, ShopProducts, Model, Brand


class Command(BaseCommand):
    help = "Create new shop and load initial data"

    def handle(self, *args, **options):
        data = [
            ("Cables de Bujías", "Geely - CK", 15, 8, 25, ""),
            ("Defensas Delanteras", "Geely - CK", 2, 40, 70, ""),
            ("Filtros de aceite", "Geely - CK", 103, 1.5, 5, ""),
            ("Filtros de Gasolina", "Geely - CK", 104, 2, 5.5, ""),
            ("Manillas Externas", "Geely - CK", 14, 15, 55, "juego"),
            ("Manillas interiores Plásticas", "Geely - CK", 10, 9, 25, "juego"),
            ("Inyectores", "Geely - CK", 10, 20, 35, "juego"),
            ("Rodamientos delanteros", "Geely - CK", 30, 6.5, 15, "c/u"),
            ("Intermitentes", "Geely - CK", 20, 5, 10, "par modernos"),
            ("Paso a Paso", "Geely - CK", 20, 6, 18, ""),
            ("Forro de palanca de  emergencia", "Geely - CK", 8, 3, 15, ""),
            ("Forro de palanca", "Geely - CK", 10, 5, 20, ""),
            ("Purificador", "Geely - CK", 5, 20, 40, "con filtro"),
            ("Filtros de purificador", "Geely - CK", 20, 3, 8, ""),
            ("Mangueras del purificador", "Geely - CK", 5, 4, 8, "c/u"),
            ("Condensador", "Geely - CK", 2, 35, 70, ""),
            ("Aforador", "Geely - CK", 24, 25, 60, ""),
            ("Bomba hidráulica", "Geely - CK", 13, 40, 90, ""),
            ("Bomba de cloche Principal", "Geely - CK", 15, 13, 25, ""),
            ("Pantallas delanteras (Focos)", "Geely - CK", 10, 85, 165, "par "),
            ("Neblineros delanteros", "Geely - CK", 10, 10, 35, "par "),
            ("Pantalla de música", "Geely - CK", 15, 45, 130, ""),
            ("Brazos limpiaparabrisas", "Geely - CK", 5, 10, 20, "par "),
            ("Sistema limpiaparabrisas", "Geely - CK", 4, 8, 20, ""),
            ("Parabrisas", "Geely - CK", 5, 55, 180, ""),
            ("Botaguas", "Geely - CK", 18, 12, 45, "juego"),
            ("Motor de arranque", "Geely - CK", 6, 24, 60, ""),
            ("Sensor Map", "Geely - CK", 20, 9, 20, ""),
            ("Chapaletas o guarda polvos", "Geely - CK", 20, 4, 15, "juego"),
            ("Bobina", "Geely - CK", 13, 12, 35, ""),
            ("Cremallera", "Geely - CK", 2, 80, 200, "con los terminales"),
            ("Homocinética juego", "Geely - CK", 6, 90, 200, "juego"),
            ("Luces chapa", "Geely - CK", 20, 4, 10, "par "),
            ("Esféricas", "Geely - CK", 40, 5, 17, "unidad"),
            ("Kit de juntas", "Geely - CK", 20, 15, 40, ""),
            ("Compresor de Aire Acondicionado", "Geely - CK", 4, 85, 220, ""),
            ("Alternador", "Geely - CK", 3, 35, 125, ""),
            ("Careta Delantera moderna", "Geely - CK", 15, 13, 35, ""),
            ("Correas de compresor", "Geely - CK", 20, 3, 7, ""),
            ("Sensor de Temperatura", "Geely - CK", 80, 4, 12, ""),
            ("Sensor de oxígeno", "Geely - CK", 10, 15, 30, ""),
            ("Caja de fusibles euro 4", "Geely - CK", 2, 80, 110, ""),
            ("Paños de puerta Traseros", "Geely - CK", 3, 30, 40, "par "),
            ("Kit de reparación", "Geely - CK", 2, 240, 330, ""),
            ("Termostato", "Geely - CK", 10, 5, 12, ""),
            ("Cable de emergencia", "Geely - CK", 10, 6, 30, ""),
            ("Amortiguadores delanteros", "Geely - CK", 9, 40, 220, "armados"),
            (
                "Depósito agua limpiaparabrisas",
                "Geely - CK",
                10,
                10,
                35,
                "on motorcito",
            ),
            ("Bandas de freno con ABS", "Geely - CK", 8, 7, 25, "abs"),
            ("Panel de instrumentos", "Geely - CK", 5, 65, 95, "moderno"),
            ("Bóvedas", "Geely - CK", 20, 12, 20, ""),
            ("Electro ventilador", "Geely - CK", 20, 17, 40, "cada uno"),
            ("Calzos del motor grande", "Geely - CK", 15, 12, 30, ""),
            ("Juntas de puertas", "Geely - CK", 15, 20, 60, "03-31-00"),
            ("tensor de distribucion", "Geely - CK", 15, 8, 15, ""),
            ("Botonera Principal", "Geely - CK", 10, 4, 10, ""),
            ("Alfombra de pizarra", "Geely - CK", 2, 25, 35, ""),
            ("Pastillas de freno", "Geely - CK", 25, 9, 25, ""),
            ("Embellecedores de botonera", "Geely - CK", 3, 40, 75, "juego"),
            ("Embellecedores de distribucion", "Geely - CK", 10, 5, 15, "juego"),
            ("Embellecedor de parabrisas", "Geely - CK", 28, 15, 35, "juego"),
            ("Amortiguadores traseros", "Geely - CK", 14, 40, 240, "armados"),
            ("Pinzas de freno delanteras con ABS", "Geely - CK", 8, 50, 75, "par "),
            ("Bomba de cloche esclava", "Geely - CK", 10, 8, 16, ""),
            ("Bomba de freno con hidrovac", "Geely - CK", 32, 40, 130, ""),
            ("Careta Delantera antigua", "Geely - CK", 10, 11, 30, ""),
            ("Mangueras de radiador ", "Geely - CK", 10, 10, 20, "par "),
            ("Tapa de radiador", "Geely - CK", 50, 2, 5, ""),
            ("Kit de cloche", "Geely - CK", 10, 40, 120, "alta calidad"),
            ("Bieletas delanteras", "Geely - CK", 15, 7, 22, "par "),
            ("Bieletas Traseras", "Geely - CK", 18, 5, 15, "par "),
            ("Juego de Chucho", "Geely - CK", 10, 18, 35, ""),
            ("Computadora", "Geely - CK", 2, 65, 85, ""),
            (
                "Planetarias de Amortiguadores con buje de goma",
                "Geely - CK",
                24,
                7,
                12,
                "cada lado",
            ),
            ("Sensor PVC", "Geely - CK", 20, 4, 10, ""),
            ("Cierre de puertas", "Geely - CK", 20, 8, 20, ""),
            ("Evaporador", "Geely - CK", 2, 45, 75, ""),
            ("Calzo de motor izquierdo", "Geely - CK", 10, 7, 20, ""),
            ("Calzos del motor antipar", "Geely - CK", 26, 8, 25, ""),
            ("Caja de fusibles euro 3", "Geely - CK", 2, 40, 80, ""),
            ("Módulo de Control", "Geely - CK", 5, 40, 75, ""),
            ("Bujes de Parrillas", "Geely - CK", 12, 8, 15, "chico y grande"),
            ("Juego de gomas de Pedales", "Geely - CK", 5, 8, 12, ""),
            ("Reparación de Homocinética", "Geely - CK", 16, 16, 30, "c/u"),
            ("Sistema ABS", "Geely - CK", 2, 60, 140, ""),
            ("Correa de distribución", "Geely - CK", 15, 5, 15, ""),
            ("Conmutador de luces y Claxon", "Geely - CK", 10, 18, 30, "par "),
            ("Pasillos o Estribos plásticos", "Geely - CK", 9, 18, 45, "par "),
            ("Depósito de agua de radiador", "Geely - CK", 10, 3, 8, ""),
            ("Correa de Alternador", "Geely - CK", 10, 5, 8, ""),
            ("Correa hidráulica", "Geely - CK", 20, 5, 6, ""),
            ("Cable de abrir maletero y combustible", "Geely - CK", 18, 7, 15, ""),
            ("botonera pequeña de puertas", "Geely - CK", 24, 2, 6, "c/u"),
            ("Motor de limpiaparabrisas", "Geely - CK", 8, 13, 35, ""),
            ("Regulador de ventanillas electricas", "Geely - CK", 18, 13, 35, "c/u"),
            ("Sistema cinturón seguridad", "Geely - CK", 25, 20, 30, "c/u"),
            ("Caja de velocidad", "Geely - CK", 1, 360, 420, ""),
            ("Pinzas de freno delanteras sin Abs", "Geely - CK", 6, 30, 50, "par "),
            ("Discos de freno delanteros", "Geely - CK", 8, 28, 60, "par "),
            ("Juego de bujias Estandar", "Geely - CK", 12, 8, 12, "juego"),
            (
                "Cremallera de Dirección",
                "Geely - Emgrand 718",
                13,
                80,
                250,
                "con los terminales",
            ),
            ("Cables de Bujías", "Geely - Emgrand 718", 10, 7, 25, "juego"),
            ("Neblineros finos traseros", "Geely - Emgrand 718", 3, 35, 50, "juego"),
            (
                "Neblineros delanteros modernos",
                "Geely - Emgrand 718",
                7,
                20,
                65,
                "juego",
            ),
            ("Pantallas traseras led", "Geely - Emgrand 718", 3, 60, 120, "juego"),
            (
                "Bobinas de encendido electrónica Cuatro huecos",
                "Geely - Emgrand 718",
                10,
                12,
                35,
                "",
            ),
            ("Compresor", "Geely - Emgrand 718", 4, 90, 200, ""),
            ("Cinta de Timón", "Geely - Emgrand 718", 8, 12, 40, ""),
            (
                "Pantalla de música",
                "Geely - Emgrand 718",
                20,
                45,
                130,
                "android camara retroceso",
            ),
            ("Tensor", "Geely - Emgrand 718", 10, 20, 45, ""),
            ("Botaguas", "Geely - Emgrand 718", 27, 12, 45, "juego"),
            ("Bomba de cloche principal", "Geely - Emgrand 718", 4, 14, 35, ""),
            ("Bomba hidráulica", "Geely - Emgrand 718", 6, 40, 90, ""),
            ("Bomba de agua", "Geely - Emgrand 718", 24, 13, 35, ""),
            ("Calzos del motor ", "Geely - Emgrand 718", 3, 30, 150, "Los 4"),
            ("Amortiguadores delanteros", "Geely - Emgrand 718", 2, 80, 250, "armados"),
            ("Forro de palanca", "Geely - Emgrand 718", 10, 11, 25, ""),
            ("Aforador", "Geely - Emgrand 718", 16, 25, 75, ""),
            ("Juntas de puertas", "Geely - Emgrand 718", 10, 35, 70, "03-31-00"),
            ("Chapaletas", "Geely - Emgrand 718", 20, 5, 25, "juego"),
            ("Bóvedas", "Geely - Emgrand 718", 7, 30, 75, "juego"),
            (
                "Juego de Espejos Retrovisores",
                "Geely - Emgrand 718",
                5,
                35,
                85,
                "juego",
            ),
            ("Inyectores", "Geely - Emgrand 718", 5, 45, 70, "juego"),
            ("Electro ventilador", "Geely - Emgrand 718", 3, 32, 120, ""),
            ("Defensa delantera", "Geely - Emgrand 718", 3, 30, 120, ""),
            ("Careta Delantera", "Geely - Emgrand 718", 8, 12, 45, ""),
            ("Filtros de aceite", "Geely - Emgrand 718", 35, 2, 6, ""),
            ("Filtros de Gasolina", "Geely - Emgrand 718", 74, 1.5, 7, ""),
            ("Paso a paso", "Geely - Emgrand 718", 10, 10, 25, ""),
            ("Cables de emergencia", "Geely - Emgrand 718", 2, 30, 40, ""),
            (
                "Pantallas delanteras Modernas",
                "Geely - Emgrand 718",
                8,
                175,
                350,
                "par ",
            ),
            (
                "Bobinas de encendido independiente",
                "Geely - Emgrand 718",
                16,
                13,
                35,
                "c/u",
            ),
            ("Amortiguadores traseros", "Geely - Emgrand 718", 2, 130, 180, "armados"),
            ("Bomba de cloche esclava", "Geely - Emgrand 718", 5, 6.5, 17, ""),
            (
                "Pastillas de freno delanteras",
                "Geely - Emgrand 718",
                23,
                5,
                25,
                "juego",
            ),
            ("Rodamientos delanteros", "Geely - Emgrand 718", 36, 8, 25, "c/u"),
            ("Embellecedor de motor", "Geely - Emgrand 718", 4, 35, 60, ""),
            ("Esféricas", "Geely - Emgrand 718", 30, 5, 15, "c/u"),
            ("Pinzas de freno traseras", "Geely - Emgrand 718", 8, 25, 130, "par "),
            ("Kit de cloche", "Geely - Emgrand 718", 8, 50, 180, ""),
            ("Cable de Cambios", "Geely - Emgrand 718", 18, 13, 60, ""),
            ("Bomba de aceite", "Geely - Emgrand 718", 9, 13, 30, ""),
            ("Juego de Chucho de Arranque", "Geely - Emgrand 718", 5, 45, 90, ""),
            ("Parrillas delanteras", "Geely - Emgrand 718", 9, 23, 120, "par "),
            ("Juego de homocinetica", "Geely - Emgrand 718", 2, 95, 220, "par "),
            (
                "Motor soplador de aire acondicionado",
                "Geely - Emgrand 718",
                4,
                17,
                45,
                "",
            ),
            ("Bieletas delanteras", "Geely - Emgrand 718", 5, 8, 25, "par "),
            ("Carcasa de control de llaves", "Geely - Emgrand 718", 5, 4, 8, ""),
            (
                "Depósito de agua de limpiaparabrisas",
                "Geely - Emgrand 718",
                8,
                10,
                35,
                "con motorcito",
            ),
            ("Discos de freno delanteros", "Geely - Emgrand 718", 5, 30, 65, "par "),
            ("Tuerca de aforador", "Geely - Emgrand 718", 4, 8, 12, ""),
            ("Botonera principal puerta chofer", "Geely - Emgrand 718", 16, 12, 25, ""),
            (
                "Botonera principal puerta chofer con Embellecedor",
                "Geely - Emgrand 718",
                3,
                5,
                30,
                "",
            ),
            (
                "Cable de abrir maletero y combustible",
                "Geely - Emgrand 718",
                10,
                8.5,
                25,
                "",
            ),
            (
                "Panel de control Aire acondicionado",
                "Geely - Emgrand 718",
                3,
                50,
                80,
                "",
            ),
            (
                "Arnés de Cables y caja de Fusibles Exterior",
                "Geely - Emgrand 718",
                2,
                200,
                350,
                "",
            ),
            ("Modulo de aceleración", "Geely - Emgrand 718", 5, 52, 100, ""),
            ("Sistema de cinturón", "Geely - Emgrand 718", 32, 25, 35, "c/u"),
            (
                "juegos de sistema limpiaparabrisas con motor",
                "Geely - Emgrand 718",
                1,
                25,
                60,
                "",
            ),
            ("Timón", "Geely - Emgrand 718", 1, 40, 60, ""),
            ("Purificador", "Geely - Emgrand 718", 15, 13, 40, ""),
            ("Juego barredores de puertas", "Geely - Emgrand 718", 2, 15, 50, "juego"),
            (
                "Válvula de expansión de aire acondicionado",
                "Geely - Emgrand 718",
                5,
                8,
                15,
                "",
            ),
            ("Motor de limpiaparabrisas", "Geely - Emgrand 718", 2, 15, 40, ""),
            (
                "Cubos de Ruedas traseros con Rodamientos",
                "Geely - Emgrand 718",
                10,
                24,
                55,
                "c/u",
            ),
            ("Estribo plástico", "Geely - Emgrand 718", 4, 8, 35, "juego"),
            ("Flauta con inyectores", "Geely - Emgrand 718", 7, 30, 90, ""),
            ("Bujes de barra estabilizadora", "Geely - Emgrand 718", 10, 2, 8, "par "),
            ("Juegos soporte defensa", "Geely - Emgrand 718", 9, 3, 12, ""),
            ("Caja de velocidad", "Geely - Emgrand 718", 2, 366, 450, ""),
            ("Reparación de Homocinética", "Geely - Emgrand 718", 16, 15, 30, ""),
            ("botonera pequeña de puertas", "Geely - Emgrand 718", 24, 2.5, 7, ""),
            ("Pedal Electrónico", "Geely - Emgrand 718", 5, 20, 40, ""),
            ("Cremalleras electricas", "Geely - Emgrand 718", 36, 15, 35, ""),
            ("Forros de maletero", "Geely - Emgrand 718", 6, 20, 45, ""),
            ("Juego de Manillas Exteriores", "Geely - Emgrand 718", 3, 25, 70, ""),
            ("Mangueras de Subcion A/C", "Geely - Emgrand 718", 10, 8, 25, ""),
            ("Muñeca de Direccion", "Geely - Emgrand 718", 3, 30, 55, ""),
            ("Mangueras de purificadores", "Geely - Emgrand 718", 2, 5, 8, ""),
            ("Plato de Cloche", "Geely - Emgrand 718", 1, 20, 50, ""),
            ("Palabrisa delantero", "Geely - Emgrand 718", 3, 55, 400, ""),
            ("Radiador Mitsubishi", "Geely - Emgrand 820", 4, 40, 100, ""),
            ("Pantalla de música corta", "Geely - Emgrand 820", 10, 45, 150, ""),
            ("Tensor Motor chino", "Geely - Emgrand 820", 2, 35, 60, ""),
            ("Compresor", "Geely - Emgrand 820", 6, 120, 200, ""),
            ("Alternador", "Geely - Emgrand 820", 24, 57, 140, ""),
            ("Botagua", "Geely - Emgrand 820", 10, 12, 45, ""),
            ("Juntas de puertas", "Geely - Emgrand 820", 5, 30, 60, "juego"),
            ("Homocinética corta motor chino", "Geely - Emgrand 820", 8, 60, 120, ""),
            ("Homocinética larga  motor chino", "Geely - Emgrand 820", 6, 75, 130, ""),
            ("Amortiguadores traseros", "Geely - Emgrand 820", 7, 85, 320, "juego"),
            ("Bóvedas", "Geely - Emgrand 820", 10, 30, 50, "juego"),
            ("Cubos de rueda delanteros", "Geely - Emgrand 820", 7, 25, 40, "c/u"),
            ("Cable abrir capó", "Geely - Emgrand 820", 5, 10, 15, ""),
            ("Neblineros delanteros", "Geely - Emgrand 820", 5, 18, 50, "par "),
            ("Bobinas de encendido", "Geely - Emgrand 820", 4, 20, 30, "c/u"),
            ("Bomba hidráulica Motor Chino", "Geely - Emgrand 820", 10, 50, 120, ""),
            ("Motor de arranque Chino", "Geely - Emgrand 820", 2, 55, 120, ""),
            ("Motor de arranque Mitsubishi", "Geely - Emgrand 820", 4, 40, 100, ""),
            ("Bujias", "Geely - Emgrand 820", 1, 2.5, 10, "juego"),
            (
                "Bomba hidráulica Motor Mitsubishi",
                "Geely - Emgrand 820",
                2,
                50,
                120,
                "",
            ),
            ("Bieletas delanteras", "Geely - Emgrand 820", 11, 15, 30, "par "),
            ("Calzos del motor pequeño", "Geely - Emgrand 820", 7, 22, 45, "c/u"),
            ("Calzos del motor antipar", "Geely - Emgrand 820", 7, 22, 50, ""),
            (
                "Cable de abrir maletero y combustible",
                "Geely - Emgrand 820",
                7,
                15,
                30,
                "",
            ),
            ("Palabrisa delantero", "Geely - Emgrand 820", 5, 100, 700, ""),
            ("Bomba de agua Motor chino", "Geely - Emgrand 820", 8, 12, 50, ""),
            ("Parrillas delanteras", "Geely - Emgrand 820", 6, 50, 130, "par "),
            ("KIT de Cloche", "Geely - Emgrand 820", 5, 90, 180, ""),
            ("Sistema de palanca de cambios", "Geely - Emgrand 820", 2, 70, 120, ""),
            ("Defensa delantera", "Geely - Emgrand 820", 2, 35, 110, ""),
            (
                "Depósito de agua de limpiaparabrisas",
                "Geely - Emgrand 820",
                8,
                20,
                50,
                "",
            ),
            ("Cable de emergencia", "Geely - Emgrand 820", 3, 20, 80, ""),
            ("Tapa de tanque de Gasolina", "Geely - Emgrand 820", 5, 18, 30, ""),
            ("Junta de Maletero", "Geely - Emgrand 820", 5, 5, 10, ""),
            ("Juego de tapasoles", "Geely - Emgrand 820", 4, 40, 70, "par "),
            ("Planetarias de Amortiguadores", "Geely - Emgrand 820", 6, 20, 30, "c/u"),
            ("Cable de Cambios", "Geely - Emgrand 820", 7, 18, 70, ""),
            ("Flauta con inyectores", "Geely - Emgrand 820", 3, 70, 140, ""),
            ("Discos de freno traseros", "Geely - Emgrand 820", 4, 55, 80, "par "),
            ("Reparación Homocinética", "Geely - Emgrand 820", 5, 25, 40, "c/u"),
            ("Electro ventilador", "Geely - Emgrand 820", 3, 48, 120, ""),
            ("Brazos limpiaparabrisas", "Geely - Emgrand 820", 3, 40, 55, "par "),
            ("Sistema ABS", "Geely - Emgrand 820", 2, 120, 170, ""),
            ("Motor Soplador", "Geely - Emgrand 820", 2, 40, 70, ""),
            (
                "Arnés de Cables y caja de Fusibles Exterior",
                "Geely - Emgrand 820",
                1,
                200,
                300,
                "",
            ),
            ("Filtro de aire acondicionado", "Geely - Emgrand GC6", 7, 3, 10, ""),
            ("Neblineros traseros", "Geely - Emgrand GC6", 5, 45, 75, "par "),
            ("Neblineros delanteros", "Geely - Emgrand GC6", 3, 45, 75, "par "),
            ("Defensa delantera", "Geely - Emgrand GC6", 3, 60, 200, ""),
            ("Pantallas delanteras", "Geely - Emgrand GC6", 18, 120, 250, "par "),
            ("Pantalla de música", "Geely - Emgrand GC6", 25, 45, 130, ""),
            ("Caretas Delanteras", "Geely - Emgrand GC6", 8, 35, 80, ""),
            ("Aforador", "Geely - Emgrand GC6", 20, 35, 85, ""),
            ("Botaguas", "Geely - Emgrand GC6", 8, 12, 50, "juego"),
            ("Bobina de encendido", "Geely - Emgrand GC6", 6, 13, 35, ""),
            ("Chapaletas", "Geely - Emgrand GC6", 45, 6, 25, "juego"),
            ("Caja de fusibles", "Geely - Emgrand GC6", 8, 55, 100, ""),
            ("Electro ventilador", "Geely - Emgrand GC6", 6, 22, 40, "c/u"),
            ("Paso a paso", "Geely - Emgrand GC6", 20, 8, 25, ""),
            ("Kit de cloche", "Geely - Emgrand GC6", 8, 55, 120, ""),
            (
                "Pastillas de freno delanteras",
                "Geely - Emgrand GC6",
                18,
                12,
                30,
                "juego",
            ),
            ("Bomba hidráulica", "Geely - Emgrand GC6", 2, 55, 100, ""),
            ("Bóvedas", "Geely - Emgrand GC6", 8, 30, 70, "juego"),
            ("Rodamientos delanteros", "Geely - Emgrand GC6", 20, 7, 20, "c/u"),
            (
                "Rodamientos traseros con Cubo de Rueda",
                "Geely - Emgrand GC6",
                6,
                30,
                60,
                "c/u",
            ),
            ("Bieletas Delanteras", "Geely - Emgrand GC6", 5, 5, 15, "par "),
            (
                "Juego de barredores de puertas",
                "Geely - Emgrand GC6",
                3,
                15,
                60,
                "juego",
            ),
            ("Juntas de puertas", "Geely - Emgrand GC6", 10, 30, 60, "juego"),
            (
                "Manillas interiores Plásticas",
                "Geely - Emgrand GC6",
                13,
                20,
                35,
                "juego",
            ),
            ("Cinta de Timón", "Geely - Emgrand GC6", 8, 15, 45, ""),
            ("Discos de freno", "Geely - Emgrand GC6", 3, 25, 60, "par "),
            ("Homocinética Larga", "Geely - Emgrand GC6", 2, 45, 120, ""),
            ("Parrillas delanteras", "Geely - Emgrand GC6", 8, 28, 120, "par "),
            ("Embellecedor de motor", "Geely - Emgrand GC6", 3, 34, 65, ""),
            ("Esféricas", "Geely - Emgrand GC6", 16, 7, 15, "c/u"),
            ("Homocinética corta", "Geely - Emgrand GC6", 2, 45, 120, ""),
            ("Cable de emergencia", "Geely - Emgrand GC6", 3, 9, 35, ""),
            ("Juegos brazos limpiaparabrisas", "Geely - Emgrand GC6", 3, 9, 25, "par "),
            ("Planetarias", "Geely - Emgrand GC6", 6, 7, 15, "c/u"),
            (
                "juegos de sistema limpiaparabrisas con motor",
                "Geely - Emgrand GC6",
                7,
                30,
                70,
                "",
            ),
            (
                "Depósito de agua limpiaparabrisas",
                "Geely - Emgrand GC6",
                18,
                12,
                40,
                "",
            ),
            (
                "Panel de control de aire acondicionado antiguo",
                "Geely - Emgrand GC6",
                7,
                55,
                75,
                "",
            ),
            ("Purificador automático", "Geely - Emgrand GC6", 21, 20, 35, ""),
            (
                "Panel de control de aire acondicionado moderno",
                "Geely - Emgrand GC6",
                2,
                60,
                85,
                "",
            ),
            (
                "Flauta con inyectores de motor automático",
                "Geely - Emgrand GC6",
                3,
                62,
                85,
                "",
            ),
            ("Bomba de agua automático", "Geely - Emgrand GC6", 8, 18, 40, ""),
            ("Juego de Chucho", "Geely - Emgrand GC6", 7, 40, 85, ""),
            ("Parabrisas", "Geely - Emgrand GC6", 4, 75, 400, ""),
            (
                "Motor soplador de aire acondicionado",
                "Geely - Emgrand GC6",
                3,
                25,
                60,
                "",
            ),
            ("Juegos soporte defensa", "Geely - Emgrand GC6", 8, 18, 25, "par "),
            ("Reparación de Homocinética", "Geely - Emgrand GC6", 6, 15, 30, "c/u"),
            ("Motor de arranque", "Geely - Emgrand GC6", 20, 24, 70, ""),
            (
                "Cable de abrir maletero y combustible",
                "Geely - Emgrand GC6",
                18,
                10,
                25,
                "",
            ),
            ("Alternador", "Geely - Emgrand GC6", 10, 40, 140, ""),
            ("Cuerpo de Aceleracion", "Geely - Emgrand GC6", 4, 55, 110, ""),
            ("Calzos de Parrillas", "Geely - Emgrand GC6", 14, 6, 12, "c/u"),
            (
                "Correa de distribución Automatico",
                "Geely - Emgrand GC6",
                5,
                2.5,
                10,
                "",
            ),
            ("Botaguas", "Geely - Emgrand GC9", 10, 12, 50, "juego"),
            (
                "Pantallas delanteras (Focos)",
                "Geely - Emgrand GC9",
                2,
                250,
                380,
                "juego",
            ),
            ("Parrillas", "Geely - Emgrand GC9", 3, 110, 250, "par "),
            ("Cangreja", "Geely - Emgrand GC9", 3, 55, 130, "par "),
        ]
        new_shop, _ = Shop.objects.get_or_create(
            name=Shop.WHOLESALE_SHOP_NAME,
            defaults={
                "extra_info": "Repuestos para vehículos",
            },
        )
        for product_name, model, quantity, cost_price, sell_price, extra_info in data:
            brand = Brand.objects.get(
                name=model.strip().split(" - ")[0]
            )  # Extract the brand name
            model, _ = Model.objects.get_or_create(
                name=model.strip().split(" - ")[1], defaults={"brand": brand}
            )
            product = Product.objects.filter(name=product_name, model=model).first()
            if not product:
                product = Product.objects.create(
                    name=product_name,
                    model=model,
                )

            shop_product, _ = ShopProducts.objects.update_or_create(
                shop=new_shop,
                product=product,
                defaults={
                    "quantity": quantity,
                    "cost_price": cost_price,
                    "sell_price": sell_price,
                    "extra_info": extra_info,
                },
            )
        self.stdout.write(
            self.style.SUCCESS("Successfully created Geely shop and products.")
        )
