# Generated by Django 5.1.1 on 2025-01-09 22:46

import json
from django.db import migrations, models


def convert_to_json(apps, schema_editor):
    GenericLog = apps.get_model("common", "GenericLog")
    for generic_log in GenericLog.objects.all():
        if generic_log.details:
            generic_log.details = json.dumps(eval(generic_log.details))
            generic_log.save()


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(convert_to_json),
        migrations.AlterField(
            model_name="genericlog",
            name="details",
            field=models.JSONField(null=True, verbose_name="Detalles"),
        ),
    ]
