# Generated by Django 5.1.1 on 2025-01-30 13:11

from django.db import migrations


def convert_to_json(apps, schema_editor):
    GenericLog = apps.get_model("common", "GenericLog")
    for generic_log in GenericLog.objects.all():
        if generic_log.details:
            for k, v in generic_log.details.items():
                if isinstance(generic_log.details[k], str):
                    generic_log.details[k] = {"old_value": None, "new_value": v}
            generic_log.save()


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_genericlog_details"),
    ]

    operations = [migrations.RunPython(convert_to_json, migrations.RunPython.noop)]
