# Generated by Django 5.1.1 on 2025-01-30 13:11

from django.db import migrations


def convert_strings_values_to_int(apps, schema_editor):
    GenericLog = apps.get_model("common", "GenericLog")
    for generic_log in GenericLog.objects.all():
        if generic_log.details:
            for k, v in generic_log.details.items():
                new_value = v["new_value"]
                old_value = v["old_value"]
                if isinstance(new_value, str) and new_value.isnumeric():
                    generic_log.details[k]["new_value"] = int(new_value)

                if isinstance(old_value, str) and old_value.isnumeric():
                    generic_log.details[k]["old_value"] = int(old_value)

        generic_log.save()


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_converting_logs_details_to_dict_when_create"),
    ]

    operations = [
        migrations.RunPython(convert_strings_values_to_int, migrations.RunPython.noop)
    ]
