# Generated by Django 5.1.1 on 2025-07-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_converting_logs_details_values_to_var_datatype"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericlog",
            name="extra_log_info",
            field=models.CharField(
                blank=True, null=True, verbose_name="Información adicional"
            ),
        ),
    ]
