# Generated by Django 5.1.1 on 2024-10-03 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0008_product_image'),
        ('users_app', '0002_create_default_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_app.shop'),
        ),
    ]
