# Generated by Django 5.1.1 on 2025-02-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0014_alter_sellgroup_options_sellgroup_seller"),
        ("clients_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="models",
            field=models.ManyToManyField(
                related_name="clients",
                to="business_app.model",
                verbose_name="Modelos de interés",
            ),
        ),
    ]
